### ISSUE TITLE
 中文文档中部分单词拼写似乎有误，且按照go语言规范语句后没必要加分号

### ISSUE THREAD

**Issue by geekjunyi** [go-vgo/robotgo#10]
中文文档中部分单词拼写似乎有误，且按照go语言规范语句后没必要加分号
如
`robogo.MouseClick();`
`robot.MouseToggle("down");`
似乎应为：
`robotgo.MouseClick()`
`robotgo.MouseToggle("down")`

**Comment by vCaesar** [comment]
ok,thk you,I fix it.
