### ISSUE TITLE
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by tr0mb1r** [go-vgo/robotgo#100]
- Robotgo version (or commit ref): latest
- Go version: go version go1.9.2 windows/amd64
- Gcc version: gcc (tdm64-1) 5.1.0
- Operating system and bit: Win10_x64

>go get github.com/go-vgo/robotgo
 github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2:0,
                 from ./bitmap/goBitmap.h:27,
                 from ..\..\..\go\src\github.com\go-vgo\robotgo\robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
compilation terminated.

**Comment by vcaesar** [comment]
The GCC compiler's file may be the problem, please use `mingw`.

**Comment by tr0mb1r** [comment]
doesn't help, same error(

**Comment by tr0mb1r** [comment]
Solved, should change gcc compiler in the %PATH%

**Comment by henson** [comment]
@tr0mb1r 我遇到跟你一样的问题，怎么修改环境变量？没看明白，盼详解，谢谢

**Comment by tr0mb1r** [comment]
@henson just add your GCC compiler to the %PATH%
My problem was solved with next trick:
`set PATH=C:\TDM-GCC-64\bin;%PATH%`

**Comment by henson** [comment]
@tr0mb1r 我已经设置了 TDM-GCC-64\bin 在环境变量里，还是报错

**Comment by tr0mb1r** [comment]
@henson try to install `MinGW-w64` and add it to %PATH%

**Comment by eceex** [comment]
mingw 32, dowload zlib will be solved:
https://osdn.net/projects/mingw/releases/69331

**Comment by zsdostar** [comment]
feel despair.

I tried to do:
`
brew install mingw-w64
brew install zlib

// Even I add zlib.h to robotgo/base
// Or install and make zlib
`

//  build to windows amd64, again and again
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./

// Any way, it told me when build to win amd64:

> base/zlib_util_c.h:2:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.

// but build to darwin success

- Robotgo version (or commit ref): latest
- Go version: go version go1.12.7 
- Gcc version: gcc9.1.0  (mingw-w64 6.0.0_1)
- Operating system and bit: macOs10.14.6/amd64
- Target system and bit: Win10_x64

**Comment by TenZeroTwo** [comment]
**I solved** the issue by google.
Unzip the package of zlib-x64 to the TDM-GCC dir.
[https://github.com/lowkey42/MagnumOpus/wiki/TDM-GCC-Mingw64-Installation#zlib-x64](https://github.com/lowkey42/MagnumOpus/wiki/TDM-GCC-Mingw64-Installation#zlib-x64)

对方啥阵型啊？

**Comment by vcaesar** [comment]
All code tests and C dependencies use MinGw-w64, TDM-GCC has not been tested.

**Comment by vcaesar** [comment]
All code tests and C dependencies use MinGw-64, TDM-GCC has not been tested.
But you can compile `lpng and lzib` yourself, and you can download `https://sourceforge.net/projects/mingw-w64/files/ x86_64-posix`.

**Comment by CarsonSlovoka** [comment]
For OS: `windows`

this [answer](https://stackoverflow.com/a/72424179/9935654) may help to you

**Comment by Enginebeck** [comment]
> **I solved** the issue by google. Unzip the package of zlib-x64 to the TDM-GCC dir. https://github.com/lowkey42/MagnumOpus/wiki/TDM-GCC-Mingw64-Installation#zlib-x64
> 
> 对方啥阵型啊？

This solution works for me, I record what I've done in [this article](https://www.yuque.com/docs/share/ca6c5479-19ad-4c9f-843e-6662feb609a6?#).
