### ISSUE TITLE
Undefined symbols for architecture x86_64: "_inflateValidate", referenced from: _png_inflate_claim in libpng.a(pngrutil.o)

### ISSUE THREAD

**Issue by Shggz** [go-vgo/robotgo#102]
- Robotgo version (or commit ref): Latest commit 50ce138
- Go version: go version go1.9.2 darwin/amd64
- Gcc version: Apple LLVM version 9.0.0 (clang-900.0.39.2)
- Operating system and bit: macOS Sierra 10.12.6 64bit

~ go get github.com/go-vgo/robotgo
github.com/go-vgo/robotgo
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(png.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngread.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwrite.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngmem.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngget.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngset.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngtrans.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngerror.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwio.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/shgz/go/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrio.o)) was built for newer OSX version (10.13) than being linked (10.12)
Undefined symbols for architecture x86_64:
  "_inflateValidate", referenced from:
      _png_inflate_claim in libpng.a(pngrutil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1

**Comment by vcaesar** [comment]
Please upgrade to OSX 10.13 or your own system to compile and replace `libpng.a`. If there is an earlier version of the system, I may downgrade in the future.
