### ISSUE TITLE
Error when installing for windows

### ISSUE THREAD

**Issue by cmconnor** [go-vgo/robotgo#104]
When I try installing on Windows 10, I get the below error:

# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/snprintf_c.h:319:0,
                 from ./bitmap/../base/str_io_c.h:4,
                 from ./bitmap/goBitmap.h:27,
                 from ..\github.com\go-vgo\robotgo\robotgo.go:45:
./bitmap/../base/snprintf.h:39:12: error: conflicting types for 'asnprintf'
 extern int asnprintf (char **ptr, size_t str_m, const char *fmt, /*args*/ ...);
            ^~~~~~~~~
In file included from /usr/include/ctype.h:4:0,
                 from /usr/include/w32api/winnt.h:16,
                 from /usr/include/w32api/minwindef.h:163,
                 from /usr/include/w32api/windef.h:8,
                 from /usr/include/w32api/windows.h:69,
                 from ./screen/../base/os.h:28,
                 from ./screen/../base/types.h:5,
                 from ./screen/goScreen.h:11,
                 from ..\github.com\go-vgo\robotgo\robotgo.go:42:
/usr/include/stdio.h:288:8: note: previous declaration of 'asnprintf' was here
 char * _EXFUN(asnprintf, (char *__restrict, size_t *__restrict, const char *__restrict, ...)
        ^
In file included from ./bitmap/../base/snprintf_c.h:319:0,
                 from ./bitmap/../base/str_io_c.h:4,
                 from ./bitmap/goBitmap.h:27,
                 from ..\github.com\go-vgo\robotgo\robotgo.go:45:
./bitmap/../base/snprintf.h:40:12: error: conflicting types for 'vasnprintf'
 extern int vasnprintf(char **ptr, size_t str_m, const char *fmt, va_list ap);
            ^~~~~~~~~~
In file included from /usr/include/ctype.h:4:0,
                 from /usr/include/w32api/winnt.h:16,
                 from /usr/include/w32api/minwindef.h:163,
                 from /usr/include/w32api/windef.h:8,
                 from /usr/include/w32api/windows.h:69,
                 from ./screen/../base/os.h:28,
                 from ./screen/../base/types.h:5,
                 from ./screen/goScreen.h:11,
                 from ..\github.com\go-vgo\robotgo\robotgo.go:42:
/usr/include/stdio.h:312:8: note: previous declaration of 'vasnprintf' was here
 char * _EXFUN(vasnprintf, (char *, size_t *, const char *, __VALIST)
        ^

**Comment by vcaesar** [comment]
What is your GCC version?

**Comment by cmconnor** [comment]
It looks like I am on GCC 6.4.0-4
![image](https://user-images.githubusercontent.com/4389473/35354553-2bcc65a4-00ff-11e8-9b5d-4defcde7dcd1.png)

**Comment by vcaesar** [comment]
The GCC compiler's file may be the problem, please try to use MinGW-w64.

**Comment by ivzhh** [comment]
If you are using MSys2, try the following:

```
pacman -S mingw-w64-x86_64-gcc

export GO111MODULE=on
export GOOS=windows
export GOARCH=amd64
export CGO_ENABLED=1
export CC=x86_64-w64-mingw32-gcc
export CXX=x86_64-w64-mingw32-g++
```
