### ISSUE TITLE
KeyEvent has bug with keypress "Esc".

### ISSUE THREAD

**Issue by wilon** [go-vgo/robotgo#105]
Win7 sys.  

 1.  In dir `go-vgo/robotgo`, run  `go run examples/event/main.go`

 2.  When show `--- Please press v---`, keypress `Esc` many times.

 3.  Show error `An unknown hook error occurred. (0)`

Hope to solve it. thanks.

**Comment by vcaesar** [comment]
I will try to update it.

**Comment by wilon** [comment]
https://github.com/go-vgo/robotgo/blob/master/event/goEvent.h#L31,L51

This is default setting.
```go
// If the escape key is pressed, naturally terminate the program.
```
