### ISSUE TITLE
Mouse button pressed?

### ISSUE THREAD

**Issue by Mebus** [go-vgo/robotgo#108]
Hallo,

how can I figure out if the left or right mouse button have been pressed?

Mebus

**Comment by vcaesar** [comment]
you can use `robotgo.AddEvent("mleft")` or `robotgo.AddEvent("mright")`.

**Comment by Mebus** [comment]
This doesn't really work, because it blocks the code. If I put it in a go routine, the program also crashes after some time.

**Comment by vcaesar** [comment]
Please see #98 .
