### ISSUE TITLE
too many arguments in call to robotgo.MouseToggle

### ISSUE THREAD

**Issue by qizexi** [go-vgo/robotgo#11]
代码如下：
package main

import (
	"time"

	"github.com/go-vgo/robotgo"
)

func main() {
	time.Sleep(5e9)

	robotgo.MoveMouse(0, 0)
	robotgo.MouseToggle("down")
	robotgo.DragMouse(100, 100)
	robotgo.MouseToggle("up")
}

**Comment by vCaesar** [comment]
Thx you,Documentation have err,I will fix it

**Comment by vCaesar** [comment]
I fix it,If ok I will close it
