### ISSUE TITLE
FindBitmap not working on MAC OS X El capitan

### ISSUE THREAD

**Issue by jurmeneta** [go-vgo/robotgo#111]
First of all, thanks for your amazing work!

I'm using the functions captureScreen, openBitmap and findBitmap.

When I run this code in ubuntu, it works. But not in MAC.

Is there any reason why?

- Robotgo version (or commit ref): v0.48.0
- Go version: go version go1.8
- Gcc version: Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
- Operating system and bit: MAC OS X El capitan
- Can you reproduce the bug at:
  - [X] Yes
- Provide example code: 

 ```Go
func main() {

	bitmap := robotgo.CaptureScreen(740, 140, 100, 50)
	fmt.Println("CaptureScreen...", bitmap)

	robotgo.SaveBitmap(bitmap, "double.png")

	doubleImgBit := robotgo.OpenBitmap("double.png")
	fmt.Println("openBitmap...", doubleImgBit)

	fx, fy := robotgo.FindBitmap(doubleImgBit)
	fmt.Println("FindBitmap------", fx, fy)
} 
```
Output: 

CaptureScreen... &{0x6800000 200 100 832 32 4 [99 115 115 116 111 114]}
openBitmap... &{0x600c000 200 100 600 24 3 [0 0 0 0 0 0]}
FindBitmap------ 1 1

**Comment by wilon** [comment]
`fx, fy := robotgo.FindBitmap(doubleImgBit, robotgo.CaptureScreen(), 0.01)`
Try it again.
And open a colorful image when run this script. Make sure your `double.png` not monochromatic.

**Comment by vcaesar** [comment]
Make sure your picture is not monochrome or common.

**Comment by jurmeneta** [comment]
Thanks for your comments!

How can I know if the picture is monochromatic or not? I use the function "captureScreen" in order to create that image.

So I should be the same that I try to find later with "findBitmap" function.

Furthermore, why this code runs perfectly on Linux?

Thanks for your help!

**Comment by vcaesar** [comment]
Maybe I will add a API.

**Comment by jurmeneta** [comment]
Sounds great.

But, why the same code works perfectly on linux and not on Mac OS X?

Thanks for your help!

**Comment by vcaesar** [comment]
This method and code is normal on my mac.

**Comment by vcaesar** [comment]
If a platform doesn't work, try updating the code.
