### ISSUE TITLE
Click at center of given Bitmap

### ISSUE THREAD

**Issue by GeorgSteyn** [go-vgo/robotgo#112]
Hello

Currently I don't see a method to find the center of a Bitmap and clicking on it.
Any suggestions on how to do this.
I would suggest this as an feature.

**Comment by GeorgSteyn** [comment]
I [found](https://gist.github.com/sergiotapia/7882944) a method to do this using the default packages. Don't know if you want to do it that why.

```golang
func getImageDimension(imagePath string) (int, int) {
	file, err := os.Open(imagePath)
	defer file.Close()
	if err != nil {
		fmt.Println(err)
	}

	image, _, err := image.DecodeConfig(file)
	if err != nil {
		fmt.Println(imagePath, err)
	}
	return image.Width, image.Height
}
```

**Comment by vcaesar** [comment]
`.png image: unknown format`, use the following method is better :
```Go
func getImageDimension(imagePath string) (int, int) {
	bitmap := robotgo.OpenBitmap(imgPath)
	gbit := robotgo.ToBitmap(bitmap)

	fmt.Println("gbit...", gbit.Width, gbit.Height)

	x := gbit.Width / 2
	y := gbit.Height / 2

	return x, y
}
```

**Comment by GeorgSteyn** [comment]
Oh, Yes I found that issues and fixed my imports...BUT your answer is AWESOME @vcaesar 
Thank You very much !!!

**Comment by vcaesar** [comment]
Ok, I updated your sample code, so that someone encountered the same problem reference.
