### ISSUE TITLE
Capturing screen question

### ISSUE THREAD

**Issue by lflserg** [go-vgo/robotgo#113]
Hello, I am trying to use this awesome library for screencapture, but it returns MMBitmapRef and actually I cannot get how to convert this to byte[] or image types golang supports. How can I do that? Please, help

**Comment by vcaesar** [comment]
You can save the image and then manipulate the image.

**Comment by lflserg** [comment]
@vcaesar  there is a performance question, as I am going to use image recognition like opencv lib, there should be a way to get pure data out there. Is this really the only way? What are the reasons behind this? Memory management?

**Comment by lflserg** [comment]
@vcaesar  btw is there a way to get image of window not the screen?

**Comment by vcaesar** [comment]
I will consider adding a similar conversion method. You can set the length, breadth and width, but not yet able to intercept a window, but you can activate the window.

**Comment by lflserg** [comment]
@vcaesar Cool! Your library is quite complete, but adding similar to FindWindow/EnumWindow  and GetWindowRect functionality as well as method for retrieving raw data will eliminate need in others like 	github.com/lxn/win and github.com/shirou/w32 and in writing own code

**Comment by vcaesar** [comment]
```Go
fpid, err := robotgo.FindIds("Google")
  if err == nil {
    fmt.Println("pids...", fpid)

    if len(fpid) > 0 {
      robotgo.ActivePID(fpid[0])

      robotgo.Kill(fpid[0])
    }
  }

  robotgo.ActiveName("chrome")
```
Similar to `FindWindow/EnumWindow`.

**Comment by lflserg** [comment]
@vcaesar yes, I`ve looked through available apis. But why I am asking is because of my particular use case, as i need to find a window to capture screen from it.

**Comment by vcaesar** [comment]
Closed because of the new API, you can convert bitmap to bytes. About FindWindow/EnumWindow should not be in this issue.
