### ISSUE TITLE
Method to Open/Read base64 bitmap

### ISSUE THREAD

**Issue by GeorgSteyn** [go-vgo/robotgo#114]
In my case I am saving images in a Database and querying them from Golang and want to use the image base64 for FindBitmap etc.

**Comment by vcaesar** [comment]
There is a similar problem in front, I will consider adding a similar conversion method.

**Comment by GeorgSteyn** [comment]
Thank You Very much. I would really like it if you consider doing this.

**Comment by GeorgSteyn** [comment]
Currently, I am going to temporary save the images and then open it.

**Comment by vcaesar** [comment]
Closed because of the new API, you can convert bitmap to bytes.
