### ISSUE TITLE
not enough arguments in call to robotgo.CaptureScreen

### ISSUE THREAD

**Issue by qizexi** [go-vgo/robotgo#12]
package main

import (
	"time"

	"github.com/go-vgo/robotgo"
)

func main() {
	time.Sleep(1e9)

	robotgo.CaptureScreen()
}

这个函数必须转参数！

**Comment by vCaesar** [comment]
Now it must;x, y, w, h;I will Consider optimization

**Comment by vCaesar** [comment]
I optimization it.if ok i will close it.
