### ISSUE TITLE
[FindBitmap] Image not on screen behaviour

### ISSUE THREAD

**Issue by GeorgSteyn** [go-vgo/robotgo#127]
- Robotgo version (or commit ref): 363c53827509ea679eccebd162a7b6ad5f25b2e8
- Go version: 1.10.1
- Gcc version: 7.3.1 20180312
- Operating system and bit:  Linux amd64 (Manjaro Linux)
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant
- Provide example code: 
    ```Go
   x, y := robotgo.FindBitmap(image)
    ```
## Description
If the image is not on the screen it takes about 5 -8 seconds before the FindBitmap function exits with -1, -1.

I would expect it should exit almost immediately if there is not an image on the screen. In my case with 0.5 tolerance, it should take about 400 to 500 ms?

...

**Comment by vcaesar** [comment]
I will test it.

**Comment by wilon** [comment]
Hi there, I happen to research the subject of `tolerance`, here some code for test time:
```go
package main

import (
	"fmt"
	"time"

	"github.com/go-vgo/robotgo"
)

func main() {
	toleranceArr := []float64{0.0, 0.05, 0.1, 0.15, 0.2, 0.5}
	widthArr := []int{10, 20}
	whereBitmap := robotgo.CaptureScreen()
	for _, width := range widthArr {
		findBitmap := robotgo.CaptureScreen(100, 100, width, width)
		for _, tolerance := range toleranceArr {
			ts := time.Now()
			for i := 0; i < 500; i++ {
				robotgo.FindBitmap(findBitmap, whereBitmap, tolerance)
			}
			te := time.Now()
			fmt.Println("tolerance:", tolerance, "bitmap width:", width, te.Sub(ts))
		}
		robotgo.FreeBitmap(findBitmap)
	}
}
```
And res:
```log
tolerance: 0    bitmap width: 10 514.651836ms
tolerance: 0.05 bitmap width: 10 716.26998ms
tolerance: 0.1  bitmap width: 10 807.739341ms
tolerance: 0.15 bitmap width: 10 2.573681655s
tolerance: 0.2  bitmap width: 10 2.496832671s
tolerance: 0.5  bitmap width: 10 3.683593ms

tolerance: 0    bitmap width: 20 1.146353824s
tolerance: 0.05 bitmap width: 20 2.376297863s
tolerance: 0.1  bitmap width: 20 3.312433795s
tolerance: 0.15 bitmap width: 20 16.896313353s
tolerance: 0.2  bitmap width: 20 17.218792505s
tolerance: 0.5  bitmap width: 20 18.008751025s
```

**My conclusion is:** 

`robotgo.FindBitmap(findBitmap, whereBitmap, tolerance)`

`findBitmap, whereBitmap` to be as small as possible.

`tolerance` set `0.1`

**Comment by GeorgSteyn** [comment]
Hello @vcaesar  
Did you get time yet to test this issue?
I see this issue is added to a milestone.

This is one issue that stops me from using this AWESOME Library.

**Comment by vcaesar** [comment]
I just did a test on mac, except that some link warning did not show your problem, I will test on Linux later.
Code:
```Go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {
	sbit := robotgo.CaptureScreen()
	fx, fy := robotgo.FindPic("test.png", sbit, 0.5)

	fmt.Println("FindBitmap...", fx, fy)
}
```
```
FindBitmap... -1, -1
```

**Comment by vcaesar** [comment]
I called 100 times FindBitmap() on Ubuntu, without your problem. Please tell me how to reproduce it.

**Comment by GeorgSteyn** [comment]
I will test again and make sure. Maybe I am doing wrong or something.
Will let you know as soon as I test it.

Thanks for your time

**Comment by ltpyt** [comment]
when i test this one, and ex grab a little area as the test.png with snipping tool, this is the test.png i load and try to find in the screenshot :  

![test](https://user-images.githubusercontent.com/44342048/49313978-8c34e900-f51b-11e8-8770-bc2bdb486bc8.png)


package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {
	sbit := robotgo.CaptureScreen()
	fx, fy := robotgo.FindPic("test.png", sbit, 0.5)

	fmt.Println("FindBitmap...", fx, fy)
}

a gif if that running - takes many many many seconds ( windows ) : 

https://i.imgur.com/kyALK2s.gifv
