### ISSUE TITLE
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by pemby** [go-vgo/robotgo#132]
- Robotgo version (or commit ref):
Current Master Branch.
- Go version:
go version go1.10.1 windows/amd64
- Gcc version:
gcc.exe (tdm64-1) 5.1.0
- Operating system and bit:
Window 7 64bit
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code: 
```
package someProject

import (
"github.com/go-vgo/robotgo"
)

func main() {
	robotgo.ScrollMouse(10, "up")
	robotgo.MouseClick("left", true)
	robotgo.MoveMouseSmooth(100, 200, 1.0, 100.0)
}
```
- Log gist:
n/a
## Description
Error: 
```
# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2:0,
                 from ./bitmap/goBitmap.h:27,
                 from ..\github.com\go-vgo\robotgo\robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
compilation terminated.
```

**Comment by vcaesar** [comment]
Please see #100, if the same problem occurs, please tell me how to reproduce it.
