### ISSUE TITLE
Memory leaks when use robotgo.CaptureScreen()

### ISSUE THREAD

**Issue by wilon** [go-vgo/robotgo#133]
- Robotgo version (or commit ref):  **latest**
- Go version:  **go version go1.10.1 windows/amd64**
- Gcc version:  **gcc version 4.8.2 (x86_64-posix-seh, Built by MinGW-W64 project)**
- Operating system and bit:  **Win7 64x**
- Provide example code:     **test.go**
 ```Go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {
	for {
		abitMap := robotgo.CaptureScreen()
		fmt.Println("abitMap...", abitMap)
	}
}
```

## Description

`go run test.go`

Then open **Win Task Manager**.

The **test.exe**'s Memory size increase 10M per second.

-

My script use the func very frequent and it must run always. So my computer out of memory when it run > 4h.

**Comment by vcaesar** [comment]
Please try to free the bitmap:
```Go
package main

import (
   "fmt"

   "github.com/go-vgo/robotgo"
)

func main() {
   for {
   	abitMap := robotgo.CaptureScreen()
   	fmt.Println("abitMap...", abitMap)
        robotgo.FreeBitmap(abitMap)
   }
}
```

**Comment by wilon** [comment]
Thanks a lot!

**Comment by vcaesar** [comment]
I added it to the example, I will consider whether the automatic recovery bitmap is appropriate.

**Comment by vcaesar** [comment]
It is recommended to use FreeBitmap to free the bitmap. If free the bitmap in CaptureScreen(), you cannot proceed to the next step.

**Comment by vcaesar** [comment]
Use `defer robotgo.FreeBitmap(bit)` to free the bitmap:
```Go
  bitmap := robotgo.CaptureScreen(12, 50, 10, 10)
  defer robotgo.FreeBitmap(bitmap)
  fx, fy := robotgo.FindPic(path, bitmap, 0.01)
  ...
  x, y := robotgo.FindBitmap(bitmap)
```
