### ISSUE TITLE
Unexpected screenshots and behavior with Screen functions.

### ISSUE THREAD

**Issue by creedr** [go-vgo/robotgo#135]
- Robotgo version (or commit ref): 5e6a618
- Go version: 1.10.1 windows/amd64
- Gcc version: mingw-w64
- Operating system and bit: Windows 10 64 bit
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go): No.
- Provide example code: 
    ```Go
package main

import (
"fmt"

"github.com/go-vgo/robotgo"

)

func main() {
// With Firefox browser maximized, get mouse coords for "Pull requests Issues"
// upperLeft: 390, 100 ----------------320, 92
// bottomRight: 530, 150
mx, my := robotgo.GetMousePos()
fmt.Println("pos:", mx, my)

x := 390
y := 100
//w := 100
//h := 50

bitmap := robotgo.CaptureScreen(x, y, 140, 50)
    robotgo.SaveBitmap(bitmap, "bitmap.png")
//robotgo.SaveCapture("bitmap.png", x, y, 140, 50)

    // Note: the navigation.PNG was saved from my computer's screenshot tool.
fx, fy := robotgo.FindPic("navigation.PNG")
fmt.Println("FindPic---------", fx, fy)
robotgo.Move(fx, fy)

openbit := robotgo.OpenBitmap("navigation.png")
ffx, ffy := robotgo.FindBitmap(bitmap)
fmt.Println("FindBitmap---------", ffx, ffy)

// robotgo.MoveClick(242, 219) // move and click

}

    ```
- Log gist:

## Description
I am having unexpected behavior from some of the Screen functions.

CaptureScreen:
I guess I'll start with a question... Where is the x,y relative to the box that is captured?
I expected the x,y to be at the top left corner, but that is not happening when I try it. For example, with my browser maximized, I try to get the box surrounding the Pull requests and Issues items in the Github header menu, i.e. 
![pullrequestissues](https://user-images.githubusercontent.com/5142567/39724780-5290f9a0-520f-11e8-9b7e-e5aebda92953.PNG)
The top left of this box is at about x,y = 390,100.
The width, height is about 140, 50.
When I do CaptureScreen(390, 100, 140, 50), I get the following screen shot where I have highlighted the point Move(390, 100), which is the top left of the box I wanted to CaptureScreen(), with yellow:
![inkedbitmap_li](https://user-images.githubusercontent.com/5142567/39724913-bc108efe-520f-11e8-848d-fdf45a677b2f.jpg)
So, it's not on center nor any corners or borders. Is it supposed to work like this?

FindBitmap / FindPic:
These two functions don't give me expected behavior either. For example, trying to find the screenshot
![pullrequestissues](https://user-images.githubusercontent.com/5142567/39725763-8297c37e-5212-11e8-8d4e-54126c220248.PNG)
The coordinates returned are 490, 122, right about where the yellow dot is in the picture below:
![inkedpullrequestissues_li](https://user-images.githubusercontent.com/5142567/39725866-cd9883f4-5212-11e8-9626-e8a6a060ab1e.jpg)

Attempting to find the browser navigation buttons:
![navigation](https://user-images.githubusercontent.com/5142567/39725902-f167607a-5212-11e8-826b-0b7e952a0292.PNG)
results in coordinates 4, 43, right about where the yellow dot is in the picture below:
![inkednavigation_li](https://user-images.githubusercontent.com/5142567/39725983-2fa7355e-5213-11e8-9651-66f51054d957.jpg)
Does it look like this is working correctly?
...

**Comment by wilon** [comment]
The find result position is wrong becase your `.png` is wrong. 
Can't solve the your problem, here is some code for reference.

```go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {

	w, h := 150, 150

	bitmap100 := robotgo.CaptureScreen(100, 100, w, h)
	robotgo.SaveBitmap(bitmap100, "bitmap100.png")

	bitmap200 := robotgo.CaptureScreen(200, 200, w, h)
	robotgo.SaveBitmap(bitmap200, "bitmap200.png")

	x, y := -1, -1

	x, y = robotgo.FindPic("bitmap100.png")
	fmt.Println("FindPic bitmap100.png ---------", x, y)

	x, y = robotgo.FindPic("bitmap200.png")
	fmt.Println("FindPic bitmap200.png ---------", x, y)

	x, y = robotgo.FindBitmap(bitmap100)
	fmt.Println("FindBitmap bitmap100 ---------", x, y)

	x, y = robotgo.FindBitmap(bitmap200)
	fmt.Println("FindBitmap bitmap200 ---------", x, y)
}

```
![image](https://user-images.githubusercontent.com/7512755/39737607-ab82c8be-52b8-11e8-8646-e0ebd2127a6b.png)

**Comment by creedr** [comment]
@wilon Thanks for your response. Your example gets my FindPic/FindBitmap coordinates right, but the CaptureScreen resulting .pngs are still shifted...

My CaptureScreen for 100,100:
![bitmap100](https://user-images.githubusercontent.com/5142567/39752161-33d4392a-5280-11e8-89d3-856248685e64.png)

My CaptureScreen for 200,200:
![bitmap200](https://user-images.githubusercontent.com/5142567/39752171-3e91e8ee-5280-11e8-900f-e8491148c1b3.png)

Still not sure whats going wrong here.

**Comment by creedr** [comment]
Okay, I found my issue. My display settings had the scaling set to 125% which was causing problems with the CaptureScreen i.e. the .png output appeared shifted, etc. Changing the scaling to 100% made everything work as expected. I had tried template matching with open-cv which was giving me unexpected results as well, making me think there was something wrong with my own system.

I'm not aware of any screen scaling options in robotgo, is that something we could implement? (I may check into this some other time when I get a chance.)

**Comment by creedr** [comment]
Windows display scaling issue. See [comment above](https://github.com/go-vgo/robotgo/issues/135#issuecomment-387368680).

**Comment by vcaesar** [comment]
Maybe I will add a `zoom ratio,  scale and layout` detection.

**Comment by vcaesar** [comment]
I added the GetScaleSize method on windows.
