### ISSUE TITLE
run after 6h crashed many times

### ISSUE THREAD

**Issue by TongxiJi** [go-vgo/robotgo#136]
- Robotgo version (or commit ref):latest version
- Go version:1.10
- Gcc version:gcc version 7.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)
- Operating system and bit:windows 10， 64bit

- Can you reproduce the bug
  - [x] Yes
```Go
	bitmap := robotgo.CaptureScreen(510, 360, 900, 350)//run interval 30s for 6h or longer
```
- Log gist:
Exception 0xc0000005 0x1 0x0 0x76fea551
PC=0x76fea551

runtime: unknown pc 0x76fea551
stack: frame={sp:0x53dcfdd0, fp:0x0} stack=[0x53cd1f28,0x53dcff28)
53dcfd50:  13111680  00000001  343a07d0  00000020
53dcfd60:  00000000  014132f8  00000000  010107cd
53dcfd70:  343a0000  343a0000  90e05662  003fd000
53dcfd80:  01410000  001339e0  53dcff68  53dcfd78
53dcfd90:  b46e291e  53dcff68  774a67b0  b46ed0c6
53dcfda0:  fffffffe  53dcfdd8  77475cc3  c0000017
53dcfdb0:  001339e0  001339e0  001339e0  001339e8
53dcfdc0:  00000000  774592e9  01419198  00000003
53dcfdd0: <00133980  00000000  53dcfe08  76fea488
53dcfde0:  00000000  35940000  00133980  00000000
53dcfdf0:  00000060  76f95d45  35940000  001339e0
53dcfe00:  490107cd  e00113a1  00000384  007ca5c1
53dcfe10:  00000000  35940000  001339e0  00000384
53dcfe20:  0000015e  e00113a1  000001fe  00000168
53dcfe30:  00cc0020  00000000  00b46d38  00000064
53dcfe40:  000d0007  00000208  230507f8  43f41a68
runtime: unknown pc 0x76fea551
stack: frame={sp:0x53dcfdd0, fp:0x0} stack=[0x53cd1f28,0x53dcff28)
53dcfd50:  13111680  00000001  343a07d0  00000020
53dcfd60:  00000000  014132f8  00000000  010107cd
53dcfd70:  343a0000  343a0000  90e05662  003fd000
53dcfd80:  01410000  001339e0  53dcff68  53dcfd78
53dcfd90:  b46e291e  53dcff68  774a67b0  b46ed0c6
53dcfda0:  fffffffe  53dcfdd8  77475cc3  c0000017
53dcfdb0:  001339e0  001339e0  001339e0  001339e8
53dcfdc0:  00000000  774592e9  01419198  00000003
53dcfdd0: <00133980  00000000  53dcfe08  76fea488
53dcfde0:  00000000  35940000  00133980  00000000
53dcfdf0:  00000060  76f95d45  35940000  001339e0
53dcfe00:  490107cd  e00113a1  00000384  007ca5c1
53dcfe10:  00000000  35940000  001339e0  00000384
53dcfe20:  0000015e  e00113a1  000001fe  00000168
53dcfe30:  00cc0020  00000000  00b46d38  00000064
53dcfe40:  000d0007  00000208  230507f8  43f41a68

goroutine 6 [syscall]:
github.com/go-vgo/robotgo._Cfunc_capture_screen(0x1fe, 0x168, 0x384, 0x15e, 0x0)
        _cgo_gotypes.go:340 +0x3f
github.com/go-vgo/robotgo.CaptureScreen(0x12d6bf58, 0x4, 0x4, 0x12f600a0)
        D:/projects-go/src/github.com/go-vgo/robotgo/robotgo.go:242 +0x41
main.needRestart(0x12dac300)
        xxxxxxx/room_error_check.go:24 +0x11f
main.main.func1()
## Description
crashed

**Comment by vcaesar** [comment]
I will test it.

**Comment by TongxiJi** [comment]
https://github.com/go-vgo/robotgo/issues/133
maybe this cause,Then I call   robotgo.FreeBitmap(bitmap) every time.It works fine now.
