### ISSUE TITLE
Error cross-compiling for windows/386 using xgo

### ISSUE THREAD

**Issue by jonbretman** [go-vgo/robotgo#143]
Not sure if this is a robotgo issue or an xgo issue but asking here just in case anyone can shine a light on what is going on.

Please see this xgo issue for info - https://github.com/karalabe/xgo/issues/123

**Comment by vcaesar** [comment]
I will test this tool when I have time.

**Comment by jonbretman** [comment]
@vcaesar interestingly I ended up trying to build build my app on a Windows machine and  got the same error:

```
In file included from ./bitmap/../base/str_io_c.h:2:0,
                 from ./bitmap/goBitmap.h:27,
                 from vendor/github.com/go-vgo/robotgo/robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
```

That was just `go build` and it's a 64 bit machine but when I tried to build with `GOARCH=386` I got a different error, something about `internalActive` being undefined on this line https://github.com/go-vgo/robotgo/blob/master/robotgo_mac_win.go#L13.

**Comment by krzysztofantczak** [comment]
Same issue. CGO=1 does not help. I'm building on 64bit win10 machine.

```
$ CGO=1 GOARCH=386 go build -o c2c.386.exe main.go
# click2/vendor/github.com/go-vgo/robotgo
vendor\github.com\go-vgo\robotgo\robotgo_mac_win.go:13:2: undefined: internalActive
```

Same behaviour when buildin on linux machine.

**Comment by virtuald** [comment]
To get GOARCH=386 to compile from Ubuntu 16, I had to add the following to the top of zlib_util_c.h:

```
#if defined(IS_WINDOWS)
	#if defined (__x86_64__)
		#include "../cdeps/win64/zlib.h"
	#else
		#include "../cdeps/win32/zlib.h"
	#endif
#else
	#include <zlib.h>
#endif
```

Unfortunately, now there's a linker error where it can't find libz.

**Comment by iwex** [comment]
Same issue. Ubuntu 16.04. I have zlib1g-dev installed

**Comment by iwex** [comment]
I've tried @virtuald code and I got 
`
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lz
collect2: error: ld returned 1 exit status
# github.com/go-vgo/robotgo
../../go-vgo/robotgo/window/window.h: In function ‘get_title_by_hand’:
cc1: warning: function may return address of local variable [-Wreturn-local-addr]
In file included from ../../go-vgo/robotgo/window/goWindow.h:12:0,
                 from ../../go-vgo/robotgo/robotgo.go:49:
../../go-vgo/robotgo/window/window.h:604:31: note: declared here
 char* get_title_by_hand(MData m_data){
                               ^
`

**Comment by vcaesar** [comment]
I will test it on Ubuntu 14.04.

**Comment by kongfei605** [comment]
same proble with macos 
os version:10.13.6 ,
golang version: 1.11.2.

add one line to  resove problem "cannot find zlib.h"
  38     #cgo windows CFLAGS: -I${SRCDIR}/cdeps/win64  // added to resove problem "cannot find zlib.h"
  39     #cgo windows LDFLAGS: -lgdi32 -luser32
  40     #cgo windows,amd64 LDFLAGS: -L${SRCDIR}/cdeps/win64 -lpng -lz


then ,it can't find libz. can anyone add libz.a to cdeps/win64 ? 

i add two version of libz.a, but it does not work.

**Comment by vcaesar** [comment]
Please check your environment configuration.

**Comment by ackFacu** [comment]
Similar here. Trying to install robotgo on a windows 10 64bit.
I just run go get github.com/go-vgo/robotgo and I get:

`# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2:0,
                 from ./bitmap/goBitmap.h:17,
                 from go-vgo\robotgo\robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
compilation terminated.
PS C:\Users\Facundo\go\src\github.com> go get github.com/go-vgo/robotgo
# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2:0,
                 from ./bitmap/goBitmap.h:17,
                 from go-vgo\robotgo\robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
compilation terminated.`

**Comment by xen0bit** [comment]
For anyone looking to cross compile from Ubuntu 18.04 to Windows using Mingw64 and still getting the zlib.h error.

sudo apt install libz-mingw-w64-dev

GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./
