### ISSUE TITLE
能转成其他格式文件就好了!

### ISSUE THREAD

**Issue by zsq2010** [go-vgo/robotgo#15]
老大,出个联系方式?～

**Comment by vCaesar** [comment]
Please express clearly,I don't your issue meaning.File?

**Comment by zsq2010** [comment]
What if outputting different formates of  image,for example png,gif,jpg,as we could have to convert by ourself on .bmp,which is two steps!
Especially,for me,i really want ".tif extension" pic in my application
Really appreciate for your excellent work!:)

**Comment by vCaesar** [comment]
you can save .tif,but convert you need get bitmap,save again.

**Comment by vCaesar** [comment]
I will think about or add a method.

**Comment by vCaesar** [comment]
I add it.I will close it.
