### ISSUE TITLE
Scale and ScaleX are not valid on windows10.

### ISSUE THREAD

**Issue by vcaesar** [go-vgo/robotgo#153]
- Robotgo version (or commit ref): 0.50.0.648
- Go version: 1.10.x
- Gcc version: x.x
- Operating system and bit: windows 10
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

```
- Log gist:

## Description
Set the zoom ratio to 125%, Scale and ScaleX get "dpi = 96" on windows10.

**Comment by 8023** [comment]
you can try add `syscall.NewLazyDLL("user32.dll").NewProc("SetProcessDPIAware").Call()` before `Scale()` and `ScaleX()`.
it works on my project.

**Comment by 8023** [comment]
and win10 default DPI scaling level add 175%(168) and 225%(216), you can try use `ScaleX() / 0.96` replace DPI map to support all DPI setting.

**Comment by vcaesar** [comment]
I added 175% and 225% to dpi-map. I will consider whether to implement this method on other system platforms, and refer to its display scale.
