### ISSUE TITLE
Missing docs for function Scroll

### ISSUE THREAD

**Issue by vence722** [go-vgo/robotgo#162]
Seen in source code there's a function Scroll(x, y int, args ...int) next to ScrollMouse(x int, y string). But the document for this function is missing. Please help to update the documentation.

**Comment by vcaesar** [comment]
Priority to reference the `godoc`. If there have time, I will to update the docs directory. And welcome contribution document.

**Comment by zsq2010** [comment]
Quick Reply<sup>[?](https://github.com/warpech/QuickReply)</sup>: I think this issue can be closed. The problem is solved.

**Comment by vence722** [comment]
Yes, thanks
