### ISSUE TITLE
Exported C types in external API

### ISSUE THREAD

**Issue by htmk** [go-vgo/robotgo#164]
- Robotgo version (or commit ref): current master
- Go version: doesn't apply
- Gcc version:
- Operating system and bit:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant
...
## Description
I was reading the [CGo documentation](https://golang.org/cmd/cgo/#hdr-Go_references_to_C), especially this part:

> Cgo translates C types into equivalent unexported Go types. Because the translations are unexported, a Go package should not expose C types in its exported API: a C type used in one Go package is different from the same C type used in another.

After reading the project source for a bit I noticed that some functions, like those in the bitmap category, are exposing some C types in the API, like: 

```Go
// BitmapStr bitmap from string
func BitmapStr(str string) C.MMBitmapRef {
	cs := C.CString(str)
	bit := C.bitmap_from_string(cs)
	defer C.free(unsafe.Pointer(cs))

	return bit
}
```

This could be causing some compatibility issues with the users, as they can't use the return value with outside functions.

**Comment by vcaesar** [comment]
Closed because there is no need to discuss and dogma.
