### ISSUE TITLE
Install not working on windows

### ISSUE THREAD

**Issue by threeaccents** [go-vgo/robotgo#173]
- Robotgo version (or commit ref):
6f0557305893c33da9ddb8f8aac687653ec074e8
- Go version:
tested with 1.11.1 and 1.9.1
- Gcc version:
6.3.0
- Operating system and bit:
windows 10 64 bit
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ x] Not relevant
- Provide example code:
go get github.com/go-vgo/robotgo

```bash
# github.com/go-vgo/robotgo/vendor/github.com/robotn/gohoo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```

## Description
I know a similar issue was already opened. https://github.com/go-vgo/robotgo/issues/88. However, I am 90% sure I installed a 64 bit gcc. Here is the exact GCC I installed https://osdn.net/projects/mingw/releases/

I've tested this in 2 different laptops and one aws windows 10 server. Same error every time.

**Comment by vcaesar** [comment]
Please use mingw-w64.

**Comment by threeaccents** [comment]
Hey man I reinstalled gcc using this download. https://mingw-w64.org/doku.php. Is there a flag or env variable I need to pass in to tell gcc to 64bit?

**Comment by vcaesar** [comment]
Mingw does not have 64 bits, you only need to install `mingw-w64`. Then, set environment variables, like "C:\mingw\bin".

**Comment by threeaccents** [comment]
I've done that. If I run gcc it tells me it is installed.
