### ISSUE TITLE
robotgo.Sleep() pauses application at beginning not when called

### ISSUE THREAD

**Issue by coreymgilmore** [go-vgo/robotgo#179]
- Robotgo version (or commit ref): v0.60.0.727
- Go version: 1.11.1
- Gcc version: 4.8.3
- Operating system and bit: W10 x64
- Resolution: 1440p
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [X] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
func typeStr() {
	robotgo.TypeString("Hello World")

	robotgo.Sleep(1)
	robotgo.TypeString("Hello World")

	robotgo.Sleep(1)
	robotgo.TypeString("Hello World")
}
```
- Log gist:

## Description
func Sleep() does not seem to function properly.  I expect the above code to output "Hello World", wait 1 second, and repeat.  Instead, the entire program pauses upon "go run main.go" for the time defined in Sleep() and then runs the TypeString()s one after another (instantaneously).

Is this by design?  Sleep() stops the program on run versus "where" the Sleep() func is called?

My problem is this: I am running a command to open a program (Notepad.exe) which takes a second to load.  I then want to write into that program.  I have to wait for the program to open before "writing".  Maybe this isn't even possible with robotgo...

**Comment by vcaesar** [comment]
The Sleep() method uses time.Sleep(), my test works fine.
```Go
robotgo.Sleep(2.1)
```
