### ISSUE TITLE
error occured when compiled win32 on macos

### ISSUE THREAD

**Issue by vber** [go-vgo/robotgo#182]
- Robotgo version (or commit ref): latest
- Go version: 1.8.1
- Gcc version:Apple LLVM version 10.0.0 (clang-1000.11.45.5)
- Operating system and bit: MacOS 64bit

/usr/local/go/src/runtime/cgo/gcc_libinit_windows.c:7:10: fatal error: 'windows.h' file not found

**Comment by vcaesar** [comment]
Closing is due to duplicate ( #143 ).
