### ISSUE TITLE
robotgo uses gohook package that has an incompatible gplv3 license

### ISSUE THREAD

**Issue by faik** [go-vgo/robotgo#183]
github.com/robotn/gohook is a GPLv3 licensed software. According to Apache 2 license you can't include a GPLv3 licensed software into an Apache licensed software.

This is from https://www.apache.org/licenses/GPL-compatibility.html

"Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. **However, GPLv3 software cannot be included in Apache projects.** The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law."

Also anyone using this library seeing as Apache 2 licensed without noticing this would be linking to a GPLv3 library.

**Comment by vcaesar** [comment]
Here is just import and vendor, `vendor` is the vendor. The project does not distribute and include them. You should not directly modify the code in the vendor. The project's license does not take effect for vendor.

**Comment by vcaesar** [comment]
And Robotgo is primarily distributed under the terms of "both the MIT license and the Apache License (Version 2.0)", So you can License with MIT.
