### ISSUE TITLE
MacOSX GetPixelColor() always same color

### ISSUE THREAD

**Issue by Haidy777** [go-vgo/robotgo#184]
- Robotgo version (or commit ref): 9d585cc6c4502875e690041e068038e0bdf8c47b (freshly, with go get)
- Go version: `go version go1.11.4 darwin/amd64`
- Gcc version:
`Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`
- Operating system and bit: OSX 10.14.1 64bit
- Resolution: 2560x1600

```Go
package main

import (
	"fmt"
	"github.com/go-vgo/robotgo"
)

func main() {
	for true {
  		x, y := robotgo.GetMousePos()
  		fmt.Println("pos: ", x, y)
  		color := robotgo.GetPixelColor(100, 200)
  		fmt.Println("color---- ", color)
	}
}
```

## Description
No matter where I'm on the screen, the color is always the same `#2c2e31` when I'm in OSX Dark-Mode and `#f6f6f6` in Light-Mode. Hopefully somebody knows what I'm doing wrong :)

**Comment by vcaesar** [comment]
```  		
color := robotgo.GetPixelColor(100, 200) ?  		color := robotgo.GetPixelColor(x, y)
```

**Comment by Haidy777** [comment]
Oh, thanks. I totally missed that :)
