### ISSUE TITLE
My display resolution is 3840x2160, but robotgo.GetScreenSize() gets 2560x1440. 

### ISSUE THREAD

**Issue by LonelyPale** [go-vgo/robotgo#185]
My display resolution is 3840x2160, but robotgo.GetScreenSize() gets 2560x1440. The mobile mouse that calls robotgo.MoveMouse() is within the range of 2560x1440, not 3840x2160. Where is the problem and how can I solve it? My system is win7 64 bits.

**Comment by vcaesar** [comment]
If scaling is set, try using robotgo.ScaleX().

**Comment by zouchengli** [comment]
> If scaling is set, try using robotgo.ScaleX().

'ScaleX' is deprecated

**Comment by breece1991** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
