### ISSUE TITLE
TypeStr() does not type ASCII characters

### ISSUE THREAD

**Issue by dessant** [go-vgo/robotgo#189]
With RobotGo 0.70.0 on Arch Linux both `TypeStr()` and `TypeStrDelay()` output different chars. `TypeStr()` seems to drop ASCII chars entirely.
```go
robotgo.TypeStr("山达尔星新星军团, galaxy. こんにちは世界.")
>> 山达尔星新星军こんにちは世
robotgo.TypeStr("hello")
>> 
```

```go
robotgo.TypeStrDelay("山达尔星新星军团, galaxy. こんにちは世界.", 1000)
>> q, galaxy. SkaoL.
robotgo.TypeStrDelay("hello", 1000)
>> hello
```

**Comment by vcaesar** [comment]
There are some problems on the linux platform, will be optimized with #106.

**Comment by DanielCalvo** [comment]
Just ran into this using Xubuntu 18.04 LTS and using go version go1.10.4 linux/amd64. Very annoying :(.

The good news is that KeyTap() does work, so a workaround is wrapping KeyTap() into another function:

```
func DaniTypeStr (str string, interval int){
	for _, v := range str {
		robotgo.KeyTap(string(v))
		time.Sleep(time.Duration(interval) * time.Millisecond)
	}
}
//DaniTypeStr("banana", 300)
```
