### ISSUE TITLE
fatal error: X11/Xlib-xcb.h: No such file or directory

### ISSUE THREAD

**Issue by qizexi** [go-vgo/robotgo#19]
这个我要安装哪个库呀，习惯ubuntu下的apt-get install安装。
我用apt-cache search x11-dev和apt-cache search xtest安装一些觉得合适的，但是还是依然提示呀。

**Comment by vCaesar** [comment]
sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev

**Comment by WolvenSpirit** [comment]
Since this fix also gives another compile error for record.h I will just write here the further needed package.

On ubuntu: `sudo apt-get install libxtst-dev` after the first solution.
