### ISSUE TITLE
undefined reference to __getreent

### ISSUE THREAD

**Issue by 7aske** [go-vgo/robotgo#194]
- Robotgo version (or commit ref):
- Go version: 1.11.5
- Gcc version: gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

- Log gist:
```
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\****\AppData\Local\Temp\go-link-935147523\000010.o: In function `default_logger':
/cygdrive/c/Users/****/go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/hook/logger_c.h:39: undefined reference to `__getreent'
/cygdrive/c/Users/****/go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/hook/logger_c.h:32: undefined reference to `__getreent'
C:\Users\****\AppData\Local\Temp\go-link-935147523\000010.o: In function `loggerProc':
C:\Users\****\go\src\github.com\go-vgo\robotgo\vendor\github.com\robotn\gohook/event/pub.h:90: undefined reference to `__getreent'
collect2.exe: error: ld returned 1 exit status 
```
## Description
When I used `go get [repo]` I get the same error but it seems to compile what is required to write code. Then when I try to compile the code it always fail with the same error. I have tried both cygwin and mingw (mingw going as low as version 5.4). Tried the same both on a virtual machine windows running on top of linux and on a windows machine and I get the same error. Same code compiles properly on my Manjaro installation.

**Comment by vcaesar** [comment]
Can't reproduce here, please try to update the code.

**Comment by thmzlt** [comment]
I'm getting the same error when running 0.93.1 with Go 1.16.5 windows/amd64 and gcc 10.3.0 built by MSYS2.
