### ISSUE TITLE
How to get all window handle(include child window) by its pid?

### ISSUE THREAD

**Issue by breece1991** [go-vgo/robotgo#197]
- Robotgo version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

```
- Log gist:

## Description

...

**Comment by breece1991** [comment]
how to active window get it's handle?

**Comment by breece1991** [comment]
I have solved my problem by use function GetBHandle()。 But I am still interested in this issue.

**Comment by vcaesar** [comment]
Use GetHandPid(pid) or GetHand(), see the godoc.
