### ISSUE TITLE
能获取鼠标点击事件吗，包括每个按键（左，中，又，前进，返回，dpi等）

### ISSUE THREAD

**Issue by sdvdxl** [go-vgo/robotgo#2]

**Comment by vCaesar** [comment]
你是要监听鼠标事件吗?还是模拟点击等事件?模拟鼠标和按键是可以的

**Comment by sdvdxl** [comment]
mac上用鼠标，以前用了usboverride，升级了之后有点问题。
刚发现这个包，看着不错，看了一下能全局控制鼠标键盘，但是貌似没有获取键盘按下和鼠标点击事件。
我是想通过鼠标按下前进后退键，然后发送一个 cmd+[ 或者 cmd+] ，完成例如浏览器的前进后退功能

**Comment by vCaesar** [comment]
我明白了,我会将这个建议纳入计划之中,谢谢建议

**Comment by vCaesar** [comment]
已经加入milestone: v0.10.0

**Comment by vCaesar** [comment]
我觉得termbox-go加上这个包似乎可以满足你的需求

**Comment by sdvdxl** [comment]
是这个包吗？  https://github.com/nsf/termbox-go

**Comment by vCaesar** [comment]
是的 
yes

**Comment by sdvdxl** [comment]
这个事件不是全局的，只能监控到当前程序运行的terminal中的事件

**Comment by vCaesar** [comment]
好吧,我知道了,我会在v0.10.0加入此功能

I will add it in v0.10.0

**Comment by vCaesar** [comment]
因为在10.12有个严重bug需要要解决,可能会推迟到0.20.0或者后面,bitmap应该会先上

**Comment by qizexi** [comment]
# github.com/go-vgo/robotgo
In file included from ./screen/goScreen.h:2:0,
                 from src/github.com/go-vgo/robotgo/robotgo.go:13:
./screen/screengrab_init.h:11:23: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.

我安装提示这个，该如何解决，我是ubuntu 16.04桌面系统

**Comment by vCaesar** [comment]
Please install X11 and  XTest

**Comment by sdvdxl** [comment]
完成了？

**Comment by vCaesar** [comment]
The document is being written.

**Comment by sdvdxl** [comment]
鼠标只有3个按键监听？有些鼠标是带着前进，后退的，这个能加上吗？

**Comment by vCaesar** [comment]
Please try mleft mright wheelDown wheelUp wheelLeft wheelRight,I do not use a mouse,There is only one Razer,Not so many buttons.

**Comment by vCaesar** [comment]
I can listen to the next button,But the mouse is different,Do not know is not your forward, back?
