### ISSUE TITLE
您好！ERROR

### ISSUE THREAD

**Issue by virnos** [go-vgo/robotgo#20]
github.com/go-vgo/robotgo
# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/io_init.h:4:0,
                 from ./bitmap/goBitmap.h:15,
                 from ..\github.com\go-vgo\robotgo\robotgo.go:16:
./bitmap/../base/png_io_init.h:4:17: fatal error: png.h: No such file or directory
compilation terminated.
错误: 进程退出代码 2.

**Comment by vCaesar** [comment]
What is your system?32 or 64?   Please install zlib and libpng.

**Comment by virnos** [comment]
windows 10   64位，   When last month, it was good.

**Comment by vCaesar** [comment]
Because bitmap,you neeb zlib&libpng.

**Comment by virnos** [comment]
OK,  thank you ,  me try
