### ISSUE TITLE
 compile erroe

### ISSUE THREAD

**Issue by namezhouyu** [go-vgo/robotgo#205]
# github.com/go-vgo/robotgo
../github.com/go-vgo/robotgo/keycode.go:13:16: undefined: Map
../github.com/go-vgo/robotgo/keycode.go:23:15: undefined: Map
../github.com/go-vgo/robotgo/robotgo_mac_win.go:22:9: undefined: internalGetBounds
../github.com/go-vgo/robotgo/robotgo_mac_win.go:34:2: undefined: internalActive

macos 10.14

**Comment by vcaesar** [comment]
Closed because of can not be reproduce  and unclear descriptions.

**Comment by paualberto** [comment]
Same here cross compiling to Windows from Linux.
With latest robotgo installed

```
GOARCH=amd64 GOOS=windows go build wintest.go                                                                                                                                                                                                    
# github.com/go-vgo/robotgo
../../go/src/github.com/go-vgo/robotgo/keycode.go:13:16: undefined: Map
../../go/src/github.com/go-vgo/robotgo/keycode.go:23:15: undefined: Map
../../go/src/github.com/go-vgo/robotgo/robotgo_mac_win.go:22:9: undefined: internalGetBounds
../../go/src/github.com/go-vgo/robotgo/robotgo_mac_win.go:31:12: undefined: cgetTitle
../../go/src/github.com/go-vgo/robotgo/robotgo_mac_win.go:45:2: undefined: internalActive
```

**Comment by kjcx** [comment]
../github.com/go-vgo/robotgo/keycode.go:13:16:undefined：Map 
../github.com/go-vgo/robotgo/keycode.go:23:15:undefined：Map 
.. /github.com/go-vgo/robotgo/robotgo_mac_win.go:22:9：undefined：internalGetBounds 
../github.com/go-vgo/robotgo/robotgo_mac_win.go:34:2:undefined：internalActive

macos 10.14
遇到同样的问题
