### ISSUE TITLE
oxc000007b error  when execute on windows

### ISSUE THREAD

**Issue by breece1991** [go-vgo/robotgo#206]
1. Please **speak English**, this is the language everybody of us can speak and write.
2. Please take a moment to search that an issue **doesn't already exist**.
3. Please make sure `Golang, GCC` is installed correctly before installing RobotGo.
4. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-vgo/robotgo
5. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Robotgo version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

```
- Log gist:

## Description

...

**Comment by vcaesar** [comment]
Closed because of irregularities not invalid and unclear descriptions.
