### ISSUE TITLE
Releases for this repo can be of the form vX.Y.Z instead of X.Y.Z

### ISSUE THREAD

**Issue by prashantgupta24** [go-vgo/robotgo#208]
Since you always release using `X.Y.Z`, `go mod` doesn't identify it as a valid release tag and versions your repo using the latest commit message. If you just include the `v` at the beginning of tags, then `go mod` will understand your tagging correctly.

This is how `go mod` identifies your tag as of now : 

`github.com/go-vgo/robotgo v0.0.0-20190311142943-193b4935d4b1`

if you included the `v` in the tag, it will be like `github.com/go-vgo/robotgo v0.80.0`.

![image](https://user-images.githubusercontent.com/9909241/55048236-b481af80-5004-11e9-970a-367025b70a71.png)

**Comment by vcaesar** [comment]
This will be updated later, and there is currently no bug fix version, please use the latest code.

**Comment by vcaesar** [comment]
Closed because of will be released.
