### ISSUE TITLE
XkbGetKeyboard failed to locate a valid keyboard warning

### ISSUE THREAD

**Issue by AlessioDP** [go-vgo/robotgo#211]
- Robotgo version (or commit ref): 4a98546f6fc7
- Go version: 1.12.1
- Gcc version: 8.2.1
- Operating system and bit: Arch Linux 64 bit - 5.0.4
- Resolution: 1366x768
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant
- Provide example code:

```Go
package main

import (
	"github.com/go-vgo/robotgo"
)

func main() {
	robotgo.TypeString("test")
}
```
- Log gist:
```
$ go run main.go
load_input_helper [1899]: XkbGetKeyboard failed to locate a valid keyboard!
$ test
```
## Description
When running the app it prints `load_input_helper [1899]: XkbGetKeyboard failed to locate a valid keyboard!`, the keyboard type still working.

## Additional info
Running on sway-1.0 with wlroots-0.5.0 (Wayland).
I open a new issue, even if already exists a similar one with the same name, because its different, the output is only this warning and not a segmentation fault.

**Comment by vcaesar** [comment]
Closing is due to duplicate ( #160 ) and code updated.
