### ISSUE TITLE
WriteAll is broken on windows

### ISSUE THREAD

**Issue by alexspeedfire** [go-vgo/robotgo#212]
- Robotgo version (or commit ref): v0.80.0.845 - 0d6d65418e9555ffb5a175ddd1d304418f6c0a1e
- Go version: go1.11.1 windows/amd64
- Gcc version: 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
- Operating system and bit: Windows 10 x64 1809
- Resolution: 1920 x 1080
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {
	text := "my text"
	robotgo.WriteAll(text)
	clipb, _ := robotgo.ReadAll()
	if clipb != text {
		fmt.Println("clipb != text")
		fmt.Println(clipb)
		fmt.Println(len(clipb))
	} else {
		fmt.Println("Ok")
	}
}
```
- Log gist: 
```
clipb != text

0
```
## Description
WriteAll() is broken on windows

**Comment by wuyueCreator** [comment]
It will be working correctly, when I directly call github.com/atotto/clipboard.WriteAll.
