### ISSUE TITLE
FindBitmap tolerance causes panic

### ISSUE THREAD

**Issue by lansana** [go-vgo/robotgo#215]
Trying to set a custom tolerance with `FindBitmap`, but it panics no matter what I do.

- Robotgo version (or commit ref): latest
- Go version: 1.12
- Gcc version: Latest on Mac OS
- Operating system and bit: Mac OS

This is the logic:
```
icon := robotgo.OpenBitmap("icons/icon.png")
robotgo.FindBitmap(icon, icon, 0.3) // Panics
robotgo.FindBitmap(icon, nil, 0.3) // Panics
robotgo.FindBitmap(icon, 0.3) // Panics
robotgo.FindBitmap(icon, 0, 0, 0, 0, 0.3) // Panics
```
All the panics are similar to this:
```
panic: interface conversion: interface {} is int, not robotgo._Ctype_MMBitmapRef
```
Doesn't make sense in the case of `robotgo.FindBitmap(icon, icon, 0.3)` because that follows the logic in the `FindBitmap` function.

**Comment by vcaesar** [comment]
`robotgo.FindBitmap(icon, icon, 0.1)` can't reproduce, and now supports `robotgo.FindBitmap(icon,nil, 0.1)`, `robotgo.FindBitmap(icon, 0.3)` consider whether to support.
