### ISSUE TITLE
linux input

### ISSUE THREAD

**Issue by bonly** [go-vgo/robotgo#22]
load_input_helper [1879]: Unknown keycode name 'evdev_aliases(qwerty)', please file a bug report!

linux system

**Comment by vCaesar** [comment]
What is your system?32 or 64?

**Comment by vCaesar** [comment]
virtual machine?

**Comment by thomasf** [comment]
I get this error as well


```
$ uname -a
Linux transwhale 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

```

**Comment by vCaesar** [comment]
Thk You,I will test it.

**Comment by vCaesar** [comment]
Maybe it is a serious bug,I will fix it.

**Comment by vCaesar** [comment]
I fix it,but have a IO error.Please wait.

**Comment by bonly** [comment]
archlinux 64bit

**Comment by vCaesar** [comment]
This bug is fixed, please update.
