### ISSUE TITLE
robot.TypeString cannot type keys requiring the shift button

### ISSUE THREAD

**Issue by thornycrackers** [go-vgo/robotgo#221]
- Robotgo version (or commit ref):  github.com/go-vgo/robotgo v0.0.0-20190618183610-7308e0c82e1e
- Go version: 1.12.4
- Gcc version: 8.3.0
- Operating system and bit: Archlinux 64bit

```
package main

import (
    "github.com/go-vgo/robotgo"
)

func main() {
    robotgo.TypeString("123!@#")
}
```

Sorry if I missed something in the documentation, I also tried searching past issues and didn't see anything. When I run the following code I get the following:

```
123123
```

Any value I try to send that requires the shift key just comes back as the lowercase equivalent.

**Comment by vcaesar** [comment]
Fixed by #253, #243.
