### ISSUE TITLE
Error when installing on WSL Ubuntu

### ISSUE THREAD

**Issue by djboboch** [go-vgo/robotgo#224]
When running the go get command the following error appears:

github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook
In file included from ./event/pub.h:20:0,
                 from ./event/goEvent.h:18,
                 from ../../go-vgo/robotgo/vendor/github.com/robotn/gohook/hook.go:22:
./event/../hook/x11/input_c.h:38:10: fatal error: X11/Xlib-xcb.h: No such file or directory
 #include <X11/Xlib-xcb.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.

I have go land installed corectly and the gcc compiler for ubuntu. Rebuilding dosent solve the issue

**Comment by vcaesar** [comment]
https://github.com/go-vgo/robotgo#requirements

**Comment by vcaesar** [comment]
Install the Ubuntu dependencies.
