### ISSUE TITLE
Error at go get in windows

### ISSUE THREAD

**Issue by xieccc** [go-vgo/robotgo#225]
- Go version:go1.12.5 windows/amd64
- Gcc version:8.1.0 (x86_64-win32-seh-rev0, Built by MinGW-W64 project)

- Log gist:
# github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook
...\AppData\Local\Temp\go-build107981850\b035\_x003.o: In function `eb_port_create':
.../go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/chan/eb_chan.h:382: undefined reference to `sched_yield'
...\AppData\Local\Temp\go-build107981850\b035\_x003.o: In function `eb_port_free':
.../go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/chan/eb_chan.h:350: undefined reference to `sched_yield'
.../go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/chan/eb_chan.h:341: undefined reference to `sched_yield'
...\AppData\Local\Temp\go-build107981850\b035\_x003.o: In function `cleanup_ops':
.../go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/chan/eb_chan.h:858: undefined reference to `sched_yield'
.../go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/chan/eb_chan.h:858: undefined reference to `sched_yield'
...\AppData\Local\Temp\go-build107981850\b035\_x003.o:.../go/src/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/chan/eb_chan.h:643: more undefined references to `sched_yield' follow
collect2.exe: error: ld returned 1 exit status

## Description
I am getting an error during the installation process. I don't know what happened.
...

**Comment by vcaesar** [comment]
Check the gcc environment and version.
