### ISSUE TITLE
Attempting to take screenshot of current focus window fails with Assertion failed: (bitmap != NULL), function createStringFromMMBitmap

### ISSUE THREAD

**Issue by amlwwalker** [go-vgo/robotgo#230]
- Robotgo version (or commit ref):
**version  v0.90.0.896, Sierra Nevada!**
- Go version:
**go version go1.11.4 darwin/amd64**
- Gcc version:
**Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin**
- Operating system and bit:
![image](https://user-images.githubusercontent.com/2920180/64704705-9cb0c180-d4a6-11e9-8553-d44810fa90ef.png)

- Resolution:
![image](https://user-images.githubusercontent.com/2920180/64704723-a508fc80-d4a6-11e9-8477-653221dc9ad1.png)

- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
package main

import (
	"fmt"
	"github.com/go-vgo/robotgo"
)

func main() {
	fmt.Println("version ", robotgo.GetVersion())
	activeMeta := robotgo.GetActive()
	fmt.Printf("%+v\r\n", activeMeta)
	activePid := robotgo.GetPID()
	fmt.Printf("%+v\r\n", activePid)
	activeName, err := robotgo.FindName(activePid)
	fmt.Println("error ", err)
	fmt.Printf("%+v\r\n", activeName)
	x, y, w, h := robotgo.GetBounds(activePid)
	fmt.Printf("%d, %d, %d, %d\r\n", x, y, w, h)
	bitmap := robotgo.CaptureScreen(x, y, w, h)
	defer robotgo.FreeBitmap(bitmap)
	robotgo.SaveCapture("saveCapture.png", x, y, w, h)
}

```
- Log gist:
https://gist.github.com/amlwwalker/8384c8234f521687f047fe04ab7560ff
## Description

I am attempting to grab the window the focus and then take a screen shot of it. I understand the approach to doing so is to first get the PID, then from that I can get the coordinates of the windows position and its size based on the PID and then I can use CaptureScreen to capture the window at these dimensions. Finally I can saveCapture to take a screenshot and store it.

I get an assertion failure as shown in the gist, I think the `GetBounds` is returning the wrong coordinates (I know it is, the first value is all over the place (`811008, 512, 48, 124`).

Any ideas where I am going wrong?
...

**Comment by amlwwalker** [comment]
@vcaesar hey, I see you are quite prevalent on the commits to this repo, I wondered if you maybe able to give me some hints to the above? Be great to solve this - unless there is a more robotgo way to get a screen shot of the currently focused window?

**Comment by vcaesar** [comment]
It is due to duplicate ( #210 ), and is a bug in GetBounds().

**Comment by amlwwalker** [comment]
This is not possible on OSX and I used applescript in the end. See here: https://github.com/therecipe/qt/issues/995#issuecomment-549542934

**Comment by vcaesar** [comment]
Thanks for your feedback; I cannot answer every question because time is limited, other features and projects are being developing, and the computer equipment and environment configuration are different.
