### ISSUE TITLE
How can I use “robotgo.KeyTap("ctrl", "space")” to compound key? When I want to find Spotlight search in MAC OS

### ISSUE THREAD

**Issue by qq737310694** [go-vgo/robotgo#232]
- Robotgo version (or commit ref): v0.90.0.930, Sierra Nevada!
- Go version: 1.10
- Gcc version: 7.0.0
- Operating system and bit:  Mac OS 10.10
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [-] No
  - [ ] Not relevant
- Provide example code:
![image](https://user-images.githubusercontent.com/12524129/65166861-12eb9000-da74-11e9-8546-51af48bb87b6.png)

```Go

```
- Log gist:

## Description

How can I use “robotgo.KeyTap("ctrl", "space")” to compound key? 
When I want to find Spotlight search in MAC OS.

![image](https://user-images.githubusercontent.com/12524129/65166694-c607b980-da73-11e9-8689-01507eb43eaf.png)

like the pic shows, I want to open [google chrome] use the code, can you help me please?

Thank you very much!

**Comment by qq737310694** [comment]
I found solution, thanks

**Comment by Tzxhy** [comment]
> I found solution, thanks

Hi. Can you tell me how to fix this? Thanks
