### ISSUE TITLE
robotgo.GetBounds return parameters are hard to understand 

### ISSUE THREAD

**Issue by xiusin** [go-vgo/robotgo#234]
- Robotgo version (or commit ref):
- Go version: 1.13
- Gcc version: mac 10.15
- Operating system and bit:
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
fpid, err := robotgo.FindIds("sublime text")
	if err == nil {
		fmt.Println("pids...", fpid)
		if len(fpid) > 0 {
			fmt.Println(robotgo.GetBounds(fpid[0]))
		}
	}

// retult:  933888 512 68912954 30

```

## Description

...

**Comment by vcaesar** [comment]
Closing is due to duplicate ( #210 ), it is a bug in GetBounds().
