### ISSUE TITLE
Run bin file Systerm Error "libwinpthread-1.dll was not found"

### ISSUE THREAD

**Issue by wilon** [go-vgo/robotgo#235]
- Robotgo version (or commit ref): latest
- Go version: go version go1.12.9 windows/amd64
- Gcc version: gcc version 4.8.2 (x86_64-posix-seh, Built by MinGW-W64 project)
- Operating system and bit: Win7 x86_64
- Resolution: 1280x1024
- Provide example code:

initdb.go

```Go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {
	ver := robotgo.GetVersion()
	fmt.Println("robotgo version is: ", ver)
}
```
- Run:

`go build -o initdb.exe initdb.go`

## Description

If the systerm don't have gcc env, run initdb.exe has Systerm Error `libwinpthread-1.dll was not found`. Copy the file [libwinpthread-1.dll](https://github.com/go-vgo/Mingw/blob/master/bin/libwinpthread-1.dll) to initdb.exe directory then can run success.

How can I build exe whithout the dll depend?

By the way, v0.80 and the later version appear this problem.

![0UmOXRH](https://user-images.githubusercontent.com/7512755/65815479-9b132780-e222-11e9-8986-c8af56ddc18b.jpg)

**Comment by vcaesar** [comment]
The MinGW installation instructions recommends setting

c:\minGW;c:\MinGW\bin;
to the PATH environment variable.

Normally the
```-static -static-libgcc -static-libstdc++```
linker options should work (try all 3 of them at once). But not for libwinpthread-1.dll.

Use
```
-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
```

or
```
set CGO_CXXFLAGS=-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
go build main.go
```
or 

```go build -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic```

**Comment by wilon** [comment]
Thanks a lot. According to your prompt, use the param solved the problem.

`go build -ldflags '-extldflags "-static"' -o initdb.exe initdb.go`
