### ISSUE TITLE
How to create an asynchronous event in 0.80.0?

### ISSUE THREAD

**Issue by JojiiOfficial** [go-vgo/robotgo#236]
I'am trying to create multiple events for mouse and keyboard. In the Changelog from version 0.80.0 is written that async events were added but if I create multiple events in different go-routines, no event fires on keypress.

```
	go (func() {
		for {
			ok := robotgo.AddEvent("`")
			if ok {
				fmt.Println("add events...")
			}
		}
	})()

	go (func() {
		for {
			ok := robotgo.AddEvent("mleft")
			if ok {
				fmt.Println("add events...")
			}
		}
	})()
```
No event gets fired. If I use only one goroutine instead, it works.
How to create asynchronous events then?

**Comment by vcaesar** [comment]
"AddEvents()" and "gohook" itself is asynchronous, "AddEvent()" is not.

**Comment by toby1991** [comment]
Should use https://github.com/robotn/gohook this package for hook keyboard or mouse
