### ISSUE TITLE
why KeyToggle() has no args with keyDelay？

### ISSUE THREAD

**Issue by xtlx2000** [go-vgo/robotgo#238]
why KeyToggle() has no args with keyDelay？

in robotgo.go:662, I found keyDelay is be deleted？why？

Thank you

**Comment by vcaesar** [comment]
Use "Sleep()" or "MicroSleep()", same as keyDelay.

**Comment by vcaesar** [comment]
Reference "KeyTap()" legacy code, too many features, code confusion. And here is the "SetKeyDelay()" API.
