### ISSUE TITLE
DragMouse is not worked as expected.

### ISSUE THREAD

**Issue by toby1991** [go-vgo/robotgo#241]
- Robotgo version (or commit ref):
- Go version: `go version go1.13.4 darwin/amd64`
- Gcc version: `GCCGO="gccgo"`
- Operating system and bit: macos mojave
- Resolution: `3440 x 1440`
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
type mouseDragAction struct {
	startX, startY, endX, endY int
	button string
}

// define `var a`

robotgo.MoveSmooth(a.startX, a.startY)
robotgo.DragSmooth(a.endX, a.endY, 1.0, 5.0)
```
- Log gist:

## Description
For example, I want to drag a file to another folder, use these codes, the operation cannot be done properly
...

**Comment by amaresh494** [comment]
Does anyone found a workaround for this? I'm also looking for the same feature.

**Comment by x931890193** [comment]
> Does anyone found a workaround for this? I'm also looking for the same feature.

version: ```robotgo@v0.100.10```
env: ```macOS big sur 11.4```
## This code will be use！although ``robotgo.Drag`` is  not valid now，lol
```golang
var sleep = 500
robotgo.Move(x, y) // start
robotgo.MilliSleep(sleep)
robotgo.Toggle("left")
robotgo.MilliSleep(sleep)
robotgo.Drag(dragX, dragY) // end 
robotgo.MilliSleep(sleep)
robotgo.Toggle("left", "up")
```
hope you good luck!

**Comment by vcaesar** [comment]
You just need use `robotgo.DragSmooth()`, and use `robotgo.MouseSleep = 100`.
