### ISSUE TITLE
@ Character conversion error

### ISSUE THREAD

**Issue by qimingxingyuliyang** [go-vgo/robotgo#243]
- Robotgo version (or commit ref): latest
- Go version: go1.13.4 linux/amd64
## Description
```Go
robotgo.TypeString("ssh root@192.168.1.163")
```
Use the above function but actual output  `ssh root2192.168.1.163`    
`@==> 2`

**Comment by SherlockGy** [comment]
是的，我在使用的过程当中也遇到了类似问题

**Comment by vcaesar** [comment]
There are some problems on the linux platform, will be optimized with #106 #189.
