### ISSUE TITLE
robotgo.TypeStrDelay() is confusing/counter intuitive

### ISSUE THREAD

**Issue by DanielCalvo** [go-vgo/robotgo#251]
When using robotgo.TypeStrDelay(str string, delay int), the higher the delay value passed to the function, the faster the string gets typed.

When I first looked at the function, I imagined the opposite would be true: With a higher delay value, the words would take longer to be typed. But no, the delay variable acts as a "speed" variable: The higher the delay value, the faster the text gets typed.

Would a PR be welcome with a comment on the function to clarify this behavior? I struggled quite a bit with it until I figured it out!

**Comment by vcaesar** [comment]
Closed because of non-standard, and code updated.
