### ISSUE TITLE
Trouble building vanilla robotgo in and for WIndows 10

### ISSUE THREAD

**Issue by janpfeifer** [go-vgo/robotgo#256]
## Versions

- Robotgo version (or commit ref):
- Go version: 1.13.1
- Gcc version: Cygwin 7.40-1, and TDM Gcc 5.1
- Operating system and bit: Windows 10

## Description

I hadn't yet compiled any CGO for windows, so I first tried cygwin, and it fails while compiling something in C:

```
   implicit declaration of function ‘_beginthread’; did you mean ‘OpenThread’
```

Following suggestion in [stackoverlow](https://stackoverflow.com/questions/59517128/implicit-declaration-of-function-beginthread-when-call-go-library-from-c-code) I attempted using TDM GCC instead. After a reboot and having to install git for windows (as opposed of the cygwin), I then got the error:

```
    go build  github.com/go-vgo/robotgo
   # github.com/go-vgo/robotgo
   In file included from ./bitmap/../base/str_io_c.h:2:0,
                    from ./bitmap/goBitmap.h:17,
                    from C:\Users\pfeif\go\src\github.com\go-vgo\robotgo\robotgo.go:45:
   ./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
   compilation terminated.
```

I'm not sure what to try next, I didn't find any easy way to install zlib with TDM gcc.

Any ideas/pointers ? What would be a "standard" setup to use RobotGo in windows ?

Many thanks!

**Comment by vcaesar** [comment]
Closed because of duplicates, #100. All code tests and C dependencies use MinGw-64, TDM-GCC has not been tested.
