### ISSUE TITLE
GetTitle returns either an empty string or weird strings.

### ISSUE THREAD

**Issue by gonssal** [go-vgo/robotgo#258]
- Robotgo version (or commit ref): 0.80
- Go version: 1.12.10
- Gcc version: 9.2.1
- Operating system and bit: Kubuntu 19.10
- Resolution: 1920x1080
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant

## Description
`robotgo.GetTitle()` returns an empty string when called without arguments and weird strings when called with a pid argument. The weird strings change from call to call with the window being the same. To me it seems that it might be this problem: https://github.com/go-vgo/robotgo/issues/76, but that issue was closed so I guess it should be fixed.

Example of 3 different `getTitle()` return values to the same window, printed using `fmt.Printf("%q\n", title)`:
- "0+\bP\xf4\u007f"
- "\xe0)\b\xdc\xd3\u007f"
- "\xe0)\b\x90\x8d\u007f"

---

On a side note, if I inspect the window with xprop, it shows the correct title for it.

**Comment by marang** [comment]
`func GetTitle(args ...int32) string {` -> returns a string
so what happens if you try `fmt.Printf("%s\n", title)` instead of `fmt.Printf("%q\n", title)`?

**Comment by gonssal** [comment]
I get this:
���P

And then this when trying again:
����

**Comment by DarkFighterLuke** [comment]
Same problem here.

**Comment by xxxserxxx** [comment]
Interestingly, the return value is different value every time the function(s) are called. I smell a pointer issue, but that's a wild guess.

```
package main

import (
	"fmt"
	"github.com/go-vgo/robotgo"
)

func main() {
	activeWindowPID := robotgo.GetPID()
	for x:=0; x < 5; x++ {
		fmt.Printf("title %4s  = %v\n", "", []byte(robotgo.GetTitle()))
		fmt.Printf("title(%d) = %v\n", activeWindowPID, []byte(robotgo.GetTitle(activeWindowPID)))
	}
}

```
output:
```
title       = [20 82 47 1]
title(1518) = [248 244 249 218 40 127]
title       = [226 151 208 218 40 127]
title(1518) = [230 75 61 1]
title       = [240 236 83 1]
title(1518) = [229 77 95 1]
title       = [207 238 117 1]
title(1518) = [247 246 223 218 40 127]
title       = [225 145 182 218 40 127]
title(1518) = [211 169 160 218 40 127]
```
