### ISSUE TITLE
ncollect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by huwweiP40** [go-vgo/robotgo#263]
- Robotgo version (or commit ref):11 hours ago
- Go version:go version go1.14.2 windows/amd64
- Gcc version:go version go1.14.2 windows/amd64
- Operating system and bit:windows10 1909 64bit
- Resolution:1920x1080
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ // Copyright 2016 The go-vgo Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// https://github.com/go-vgo/robotgo/blob/master/LICENSE
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
	// "go-vgo/robotgo"
)

func main() {
	ver := robotgo.GetVersion()
	fmt.Println("robotgo version is: ", ver)

	// Control the keyboard
	// key()

	// Control the mouse
	// mouse()

	// Read the screen
	// screen()

	// Bitmap and image processing
	// bitmap()

	// Global event listener
	// event()

	// Window Handle and progress
	// window()
}] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

```
- Log gist:{
	"resource": "/c:/Users/magicbook/Documents/war3/war3.go",
	"owner": "go",
	"severity": 8,
	"message": "# _/C_/Users/magicbook/Documents/war3\nc:\\go\\pkg\\tool\\windows_amd64\\link.exe: running gcc failed: exit status 1\nC:\\Users\\MAGICB~1\\AppData\\Local\\Temp\\go-link-349977503\\go.o: file not recognized: file format not recognized\r\ncollect2.exe: error: ld returned 1 exit status\n\n",
	"source": "go",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 67
}

## Description
I installed C:\MinGW\bin using mingw-get-setup, but I encountered a compilation error, I also set the environment variables, but it seems that the collect2.exe error still exists. At the same time, I also tried to download and compile https://github.com/go-vgo/Mingw32, but the compilation was not successful. I ask for help locating the problem. I am using an amd processor, I do not know if it is related to the processor.
...

**Comment by vcaesar** [comment]
You should install 64-bit MinGW-w64, just check your gcc environment. And a long time ago version not need to compiled libpng. #100
