### ISSUE TITLE
mright

### ISSUE THREAD

**Issue by rajkumarks7** [go-vgo/robotgo#265]
1. Please **speak English**, this is the language everybody of us can speak and write.
2. Please take a moment to **search** that an issue **doesn't already exist**.
3. Please make sure `Golang, GCC` is installed correctly before installing RobotGo.
4. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-vgo/robotgo
5. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Robotgo version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

```
- Log gist:

## Description
i got issue with the right click of mouse in order to track number of  right click of mouse we use the AddEvent("mright") mouse but it is not working when we click the right key of mouse but it is working for the right arrow in keyboard please solve this issue.
...

**Comment by wilon** [comment]
Try to use `AddMouse("right")`
Reference: https://github.com/go-vgo/robotgo/blob/master/hook.go#L146
