### ISSUE TITLE
Cannot bind more than one event

### ISSUE THREAD

**Issue by Zarovzky** [go-vgo/robotgo#266]
I would like to add my own functions for every key pressed but I am unable to get it to trigger for more than 1 key.

So the main function looks like this:

func main() {
    go addKeyListen("l")
    go addKeyListen("k")
}

The wrapper function:

func addKeyListen(key string) {
    for {
        if ok := robotgo.AddEvent(key); ok {
            fmt.Println("Pressed "+key)
        }
    }
}

After pressing L all I am getting is "Pressed l" and multiple times but I can solve that with a flag. Pressing K doesn't print anything.

Testing this from windows 10 with MinGW64 version x86_64-8.1.0-posix-seh-rt_v6-rev0
go version go1.13.1 windows/amd64

**Comment by vcaesar** [comment]
Use "robotgo.AddEvents()"or "[gohook](https://github.com/robotn/gohook)", #236.

**Comment by Zarovzky** [comment]
when using AddEvents it does work 2-3 times, then it freezes whole computer lol
