### ISSUE TITLE
does not contain package github.com/go-vgo/robotgo

### ISSUE THREAD

**Issue by Lemo-yxk** [go-vgo/robotgo#270]
- Robotgo version (or commit ref):67bbac75ce09d500cc7d195eceec8f902ddfa1bc
- Go version:1.14
- Gcc version:Apple clang version 11.0.3 (clang-1103.0.32.59)
- Operating system and bit:Mac os 10.15.4
- Resolution:not contain package github.com/go-vgo/robotgo
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

```
- Log gist:
module github.com/go-vgo/robotgo@latest found (v0.0.0-20200519155724-baf3c322fcb1), but does not contain package github.com/go-vgo/robotgo
## Description

...

**Comment by Lemo-yxk** [comment]
db296452f1bb14ea0f95c1e559fa72587888125c
this commit is ok.

**Comment by vcaesar** [comment]
I tested it on my macos, can't be reproduced; If the problem persists, please tell me how to reproduce it.

**Comment by Lemo-yxk** [comment]
It's strange.I don't change anything today,BUT it works now. seems like web caching, thanks for your answer!
