### ISSUE TITLE
Most of the functions don't appear to work, macOS.

### ISSUE THREAD

**Issue by zac-garby** [go-vgo/robotgo#271]
- Robotgo version (or commit ref): v0.90.0.1050, MT. Rainier
- Go version: 1.13
- Gcc version: (not GCC) Apple clang version 11.0.3 (clang-1103.0.32.62)
- Operating system and bit: macOS Catalina 10.15.4, 64-bit
- Resolution: 2560x1440 (scaled from 5k)
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
package main

import (
        "github.com/go-vgo/robotgo"
        "fmt"
)

func main() {
        robotgo.TypeStr("Hello, world!")

        x, y := robotgo.GetMousePos()
        fmt.Println("pos: ", x, y)

        robotgo.MoveMouseSmooth(100, 200, 1.0, 100.0)
}
```

## Description
Most of robotgo's functions don't work. The only one that I've tried so far that *has* worked is `robotgo.GetMousePos()`.

When running my example code, no text is typed and my mouse isn't moved. All that happens is my mouse position is printed.

The same happens when running any of the example programs - barely anything happens.

**Comment by rjack** [comment]
Have you given permission to the Terminal app for Screen Recording and Accessibility under System Preferences > Security and Privacy > Privacy (assuming that your are running the example program from the Terminal)?

Until I did, your example only printed the mouse position, now it works fine.

**Comment by vcaesar** [comment]
Try to given permission to the Terminal app.

**Comment by zac-garby** [comment]
That was exactly the problem, it's working now. Thanks :)

Interestingly, I also tried running from the emacs inbuilt terminal which *does* have accessibility permissions, and it didn't work through there. Just mentioning in case anybody has the same problem.
