### ISSUE TITLE
[macOS] robotgo.GetBounds wrong result

### ISSUE THREAD

**Issue by KonstantinKuklin** [go-vgo/robotgo#273]
- Robotgo version (or commit ref): 11268cb7c223cd2c0c2d1cffec300f9e99179951
- Go version: go version go1.14.3 darwin/amd64
- Gcc version: Apple clang version 11.0.0 (clang-1100.0.33.8)
- Operating system and bit: macOS Mojave 10.14.6 x64
- Resolution:2560x1600
- Provide example code:

```Go
package main

import (
	"fmt"
	"github.com/go-vgo/robotgo"
	"os"
)

func main() {
	appName := "Chrome"
	fpid, err := robotgo.FindIds(appName)
	if err == nil {
		fmt.Println("pids... ", fpid)
		x, y, w, h := robotgo.GetBounds(fpid[0])
		fmt.Printf("x:%d,y:%d,w:%d,h:%d",x,y,w,h)
		os.Exit(0)
	}
	fmt.Printf("'%s' not found, start it pls")
}
```
- Output:
```
pids...  [770]
x:1597440,y:512,w:70684774,h:70
```

## Description
X and W always get random numbers while my Chrome window not moving.
Y and H always constants, even I move my Chrome window around workspace and resize it.
...

**Comment by vcaesar** [comment]
Closing is due to duplicate ( #230, #210 ), it is a bug in GetBounds().
