### ISSUE TITLE
robotgo.CaptureScreen() returns empty image

### ISSUE THREAD

**Issue by paul-nelson-baker** [go-vgo/robotgo#275]
- Robotgo version (or commit ref): `v0.90.1`
- Go version: go version go1.14.3 linux/amd64
- Gcc version: `gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0`
- Operating system and bit: `Linux rog-strix-g531gt 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Resolution: 1920x1080 (16:9)
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/bitmap-bytes/main.go):
  - [X] Yes (provide example code)
  The [bitmap-bytes example](https://github.com/go-vgo/robotgo/blob/master/examples/bitmap-bytes/main.go) also shows this behavior
- Provide example code:

```Go
func main() {
	// Capture the screen in the form of image.Image
	screenCaptureImage, err := captureScreenPicture()
	if err != nil {
		panic(err)
	}
	// Save it for debugging purposes
	if err := saveImage(screenCaptureImage, "screen-capture-test"); err != nil {
		panic(err)
	}
        // ....
}

func captureScreenPicture() (image.Image, error) {
	screenCaptureBitmap := robotgo.CaptureScreen()
	// This free should be safe, because we're copying the image as we convert it to our target type
	defer robotgo.FreeBitmap(screenCaptureBitmap)
	screenCaptureBytes := robotgo.ToBitmapBytes(screenCaptureBitmap)
	screenCaptureImage, err := bmp.Decode(bytes.NewReader(screenCaptureBytes))
	if err != nil {
		return nil, err
	}
	return screenCaptureImage, nil
}

func saveImage(img image.Image, name string) error {
	byteBuffer := &bytes.Buffer{}
	err := png.Encode(byteBuffer, img)
	if err != nil {
		return err
	}
	if !strings.HasSuffix(name, ".png") {
		name += ".png"
	}
	return ioutil.WriteFile(name, byteBuffer.Bytes(), 0644)
}
```
- Log gist:
```
MIT-MAGIC-COOKIE-1
```

## Description

I'm using robotgo in tandem with [pixel](https://github.com/faiface/pixel). I'm trying to take a screenshot with robotgo so I can warp and mess around with it in pixel. Ya'know, just for fun lol.

Not sure what's happening but on a fairly fresh installation of Ubuntu 20.04 LTS I'm having trouble taking screenshots (Not 100% fresh because I've installed all the dependencies listed for Ubuntu under the readme). 

`robotgo.CaptureScreen()` looks like it should be performing correctly as it appears the dimensions of the screenshot are the correct size, however, the screenshot itself is completely empty. Running the [bitmap-bytes](https://github.com/go-vgo/robotgo/blob/master/examples/bitmap-bytes/main.go) example does the same thing.

If you have any insight as to why this is happening, or what the next step in debugging is to get to the heart of the issue I'll help any way I can!

**Comment by vcaesar** [comment]
I tested it on mac and can't reproduce it, I will be test on Ubuntu.

**Comment by vcaesar** [comment]
I tested it on Ubuntu15 and can't reproduce it. If someone can reproduce it, I will test it on other versions.

**Comment by pvorontsovd** [comment]
I have the same issue on Ubuntu 20.04 LTS

- Robotgo version (or commit ref): `v1.0.0-beta3`
- Go version: `go version go1.17.1 linux/amd64`
- Gcc version: `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`
- Operating system and bit: `5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Resolution: `2560x1440`
- Provide example code:
```go
func main() {
	test := robotgo.CaptureImg(10, 10, 30, 30)
	if err := robotgo.Save(test, "test.png"); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by mattbucci** [comment]
Facing this same issue in elementary OS using the example code.
