### ISSUE TITLE
Error #cgo windows,amd64 LDFLAGS: -L${SRCDIR}/cdeps/win64 -lpng -lz

### ISSUE THREAD

**Issue by jairforero** [go-vgo/robotgo#278]
Please help to clone package with go get github.com/go-vgo/robotgo
Return Error
# github.com/go-vgo/robotgo
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lz

This error y for flag in robotgo.go in line 39
#cgo windows,amd64 LDFLAGS: -L${SRCDIR}/cdeps/win64 -lpng -lz

Please help

**Comment by vcaesar** [comment]
Closed because of duplicates, #100. All code tests and C dependencies use MinGw-64, TDM-GCC has not been tested.
But you can compile `lpng and lzib` yourself, and you can download `https://sourceforge.net/projects/mingw-w64/files/ x86_64-posix`.
