### ISSUE TITLE
 Cross Compilation(mac ->windows) error

### ISSUE THREAD

**Issue by Xuzan9396** [go-vgo/robotgo#283]
1. GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./

- Robotgo version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

![image](https://user-images.githubusercontent.com/24741439/90087635-e0afe480-dd4f-11ea-955b-acb4a3c9c113.png)

```
➜  auto_gui GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./
WORK=/var/folders/fx/9mf_z9390n791y4tpt6c0dph0000gn/T/go-build442982789
mkdir -p $WORK/b034/
cd /Users/xuzan/go/pkg/mod/github.com/go-vgo/robotgo@v0.90.2
CGO_LDFLAGS='"-g" "-O2" "-lgdi32" "-luser32" "-L/Users/xuzan/go/pkg/mod/github.com/go-vgo/robotgo@v0.90.2/cdeps/win64" "-lpng" "-lz"' /usr/local/go/pkg/tool/darwin_amd64/cgo -objdir $WORK/b034/ -importpath github.com/go-vgo/robotgo -- -I $WORK/b034/ -g -O2 ./robotgo.go
# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2,
                 from ./bitmap/goBitmap.h:17,
                 from ../../../../pkg/mod/github.com/go-vgo/robotgo@v0.90.2/robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:10: fatal error: zlib.h: No such file or directory
    2 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.

```

## Description
 mac -> windows    go build error

**Comment by J7mbo** [comment]
I also have this problem - you didn't say how you solved this @Xuzan9396 :P

**Comment by jaoye** [comment]
@J7mbo 
1. brew install mingw-w64
2. build or download [zlib](https://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/Binaries%20%2864-bit%29/zlib-1.2.5-bin-x64.zip/download) 
3. unzip zlib-1.2.5-bin-x64.zip
4. cp zlib-1.2.5-bin-x64/binl to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/bin
5. cp zlib-1.2.5-bin-x64/include to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/include
6. cp zlib-1.2.5-bin-x64/lib to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/lib
7. GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./

**Comment by Hareis** [comment]
> 7\. GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./

that is great

**Comment by acbetter** [comment]
> 2. build or download [zlib](https://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/Binaries%20%2864-bit%29/zlib-1.2.5-bin-x64.zip/download)
> 3. unzip zlib-1.2.5-bin-x64.zip
> 4. copy zlib-1.2.5-bin-x64/bin to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/bin
> 5. copy zlib-1.2.5-bin-x64/include to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/include
> 6. copy zlib-1.2.5-bin-x64/lib to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/lib

Thanks for sharing the solution!

**Comment by mrandi96** [comment]
> @J7mbo
> 
> 1. brew install mingw-w64
> 2. build or download [zlib](https://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/Binaries%20%2864-bit%29/zlib-1.2.5-bin-x64.zip/download)
> 3. unzip zlib-1.2.5-bin-x64.zip
> 4. copy zlib-1.2.5-bin-x64/bin to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/bin
> 5. copy zlib-1.2.5-bin-x64/include to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/include
> 6. copy zlib-1.2.5-bin-x64/lib to /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/x86_64-w64-mingw32/lib
> 7. GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x ./

I'm sorry for reopening this, I just run this and it resulting different kind of error. Which is
```sh
# gocv.io/x/gocv
In file included from calib3d.cpp:1:
calib3d.h:5:10: fatal error: opencv2/opencv.hpp: No such file or directory
    5 | #include <opencv2/opencv.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Anybody know the solution or workaround? Thank you.

**Comment by Xuzan9396** [comment]
mac m1 
```
copy zlib-1.2.5-bin-x64/bin/* /opt/homebrew/opt/mingw-w64/toolchain-x86_64/x86_64-w64-mingw32/bin
copy zlib-1.2.5-bin-x64/include/*  /opt/homebrew/opt/mingw-w64/toolchain-x86_64/x86_64-w64-mingw32/include
copy zlib-1.2.5-bin-x64/lib/* /opt/homebrew/opt/mingw-w64/toolchain-x86_64/x86_64-w64-mingw32/lib
 GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -x -v -ldflags "-H=windowsgui" -o daka.exe main.go
```
