### ISSUE TITLE
[Darwin/macOS] keyCodeForChar for 'a' returns 0xFFFF and functions like KeyTap returns ""

### ISSUE THREAD

**Issue by anatawa12** [go-vgo/robotgo#286]
1. Please **speak English**, this is the language everybody of us can speak and write.
2. Please take a moment to **search** that an issue **doesn't already exist**.
3. Please make sure `Golang, GCC` is installed correctly before installing .
4. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-vgo/
5. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

-  version (or commit ref): 0.90.2
- Go version: 

      $ go version
      go version go1.14.2 darwin/amd64

- Gcc version:

      $ gcc -v
      Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
      Apple clang version 11.0.0 (clang-1100.0.33.16)
      Target: x86_64-apple-darwin19.5.0
      Thread model: posix
      InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- Operating system and bit:

      $ uname -v  
      Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
      $ sw_vers
      ProductName:    Mac OS X
      ProductVersion: 10.15.5
      BuildVersion:   19F101

- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo//blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
func main() {
	println(robotgo.KeyToggle("a", "down"))
	println(robotgo.KeyToggle("a", "up"))
	println(robotgo.KeyToggle("A", "down"))
	println(robotgo.KeyToggle("A", "up"))
}
// prints empty four lines and never tapped 'a' key
```
- Log gist:

## Description

reproduced in examples/key/main.go

### first bug
keyCodeForChar('a') returns 0xFFFF so we cannot press 'A' key.
We cannot press 'B' key and '0' key because of the same reason.

### second bug
functions like KeyTap returns empty string(means no error) if keyCodeForChar returns 0xFFFF. I think they should return `"Invalid key code specified."`

**Comment by vcaesar** [comment]
I'll think about it and fix it, or give me a PR, thanks.
