### ISSUE TITLE
Click() doesn't click

### ISSUE THREAD

**Issue by rur0** [go-vgo/robotgo#288]
- Robotgo version (or commit ref): v0.90.0.940, Sierra Nevada!
- Go version: go1.15.1 linux/amd64
- Gcc version: 10.2.0
- Operating system and bit: linux (?what do you mean bit)
- Resolution: 1920x1080+0+420, 1080x1920+1920+0 (dual monitor -| configuration)
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
robotgo.Click()
```
- Log gist:

## Description
When I call robotgo.Click(), mouse doesn't click. I have 2 monitors; one horizontal and other vertical.

**Comment by rur0** [comment]
Update to latest version fixed this.

**Comment by xtlx2000** [comment]
> Update to latest version fixed this.

but i meet this question in latest version

**Comment by fragmentization** [comment]
I had a similar problem where `robotgo.Click()` would not work when the mouse clicked on another page.

**Comment by breece1991** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by fragmentization** [comment]
![image](https://github.com/go-vgo/robotgo/assets/38492317/5ecf1b6a-6b12-4f26-b9e1-4e5df4feb6cc)
第一次调用 `robotgo.Click()` 是正常，点击上图位置后，第二次触发 `robotgo.Click()` 就不正常。但如果我现在重新点击其他地方又正常了。好像是什么地方让鼠标变得不可被控制一样


```
var mu sync.Mutex
func Click(x, y int) {
	mu.Lock()
	defer mu.Unlock()
	robotgo.MovesClick(x, y)
	return
}
```
