### ISSUE TITLE
Does the method "allPressed" behavior as expected?

### ISSUE THREAD

**Issue by DarainS** [go-vgo/robotgo#290]
- Robotgo version (or commit ref):
	github.com/go-vgo/robotgo v0.90.3
	github.com/robotn/gohook v0.30.3
- Go version:
1.51
- Gcc version:
8.1
- Operating system and bit:
win64
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

- Log gist:

## Description
I read the code and find this:

```Go
func allPressed(pressed map[uint16]bool, keys ...uint16) bool {
	for _, i := range keys {
		// fmt.Println(i)
		return !pressed[i]
	}

	return true
}
```
I thought it will return true as all keys pressed otherwise false, but not likely right. 
It only checked the first key then return.
...

**Comment by vcaesar** [comment]
Fixed.
