### ISSUE TITLE
go get github.com/go-vgo/robotgo timeout error

### ISSUE THREAD

**Issue by wsilverky** [go-vgo/robotgo#291]
system: MacOS 10.15.7
Go version: 1.15.2
robotgo: latest

the error message:
 go get github.com/go-vgo/robotgo

package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix": https fetch: Get "https://golang.org/x/sys/unix?go-get=1": dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/image/bmp: unrecognized import path "golang.org/x/image/bmp": https fetch: Get "https://golang.org/x/image/bmp?go-get=1": dial tcp 216.239.37.1:443: i/o timeout

I tried many times, but it already get this error.

**Comment by wilon** [comment]
You can try [https://goproxy.io/](https://goproxy.io/)

**Comment by vcaesar** [comment]
i/o timeout, try to use proxy.

**Comment by wsilverky** [comment]
> You can try https://goproxy.io/

thanks，it's OK
