### ISSUE TITLE
bitmap

### ISSUE THREAD

**Issue by vCaesar** [go-vgo/robotgo#3]
Complete  bitmap

**Comment by moketao** [comment]
坐等 bitmap ，非常期待

**Comment by vCaesar** [comment]
As soon as possible,but global mouse key and other is a huge project

**Comment by vCaesar** [comment]
已经完成初步工作和测试,bitmap应该会比全局鼠标键盘先上,因为那个在10.12有个严重bug需要要解决,可能会推迟到0.20.0或者后面
