### ISSUE TITLE
How to find all bitmaps?

### ISSUE THREAD

**Issue by DesSolo** [go-vgo/robotgo#307]
Hey. Thanks for the project. 
Can you please tell me how you can find all the coordinates of objects on a bitmap?
Something similar to:
```go
bitmap := robotgo.OpenBitmap("images/sample.png")
target := robotgo.OpenBitmap("images/target.png")
for _, points := range robotgo.FindAllBitmaps(target, bitmap) {
	fmt.Println(points)
}
```

**Comment by vcaesar** [comment]
You can use robotgo.FindEveryBitmap(), I will improve it of late.

**Comment by DesSolo** [comment]
Thanks for the answer. I hope to add this feature.
Now `FindEveryBitmap` will only return one position https://github.com/go-vgo/robotgo/blob/master/robotgo.go#L1021

**Comment by EliosMax** [comment]
Hello, I wanted to ask you about something similar. How do I get the positions of all pixels of the same color? I'm using robotgo.GetPixelColor () in loop but it takes too long.

**Comment by vcaesar** [comment]
Both function will be added.

**Comment by EliosMax** [comment]
Thank you for your help, best regards

**Comment by vcaesar** [comment]
I added it, update and  use `FindEveryBitmap and findEveryColor`.

**Comment by DesSolo** [comment]
@vcaesar thanks for the feature!
But MPoint has only private x and y
https://github.com/go-vgo/robotgo/blob/7b583478d41766f7b65a951c992f32c6e3c2bb20/robotgo.go#L101

**Comment by vcaesar** [comment]
Updated.
