### ISSUE TITLE
Load image

### ISSUE THREAD

**Issue by nk9200014** [go-vgo/robotgo#309]
Golang 1.16 use new embed package to Embed Files.
Will there be a function like this?
```go
//go:embed img/test.png
var testPng []byte
img, _, _ := image.Decode(bytes.NewReader(testPng))
	
Bm := robotgo.ImgToBitmap(img) // <-this
fx,fy := robotgo.FindBitmap(Bm)
if fx > 0 && fy > 0 {
	// Do...
} 
```
Thank you for your answer.

**Comment by DesSolo** [comment]
`robotgo.OpenBitmap(file)` there is a method that opens an image
https://github.com/go-vgo/robotgo/blob/master/examples/bitmap/main.go#L141

**Comment by vcaesar** [comment]
This is in the plan, maybe next.
