### ISSUE TITLE
Realistic Mouse Move?

### ISSUE THREAD

**Issue by Dontmindmes** [go-vgo/robotgo#316]
Hey what's the most realistic mouse movement parameter?  like make it mouse moving look as realistic as possible 
and is it possible to make the mouse smooth move there and auto click it? if possible could someone post the code snippet

**Comment by vcaesar** [comment]
You can use:
```go
robotgo.MoveSmooth(100, 100)
robotgo.MilliSleep(100)
robotgo.Click()
```
