### ISSUE TITLE
Bitmap and libpng

### ISSUE THREAD

**Issue by hitakiri** [go-vgo/robotgo#32]
I compile libpng (windows 64)
Where i shoud put png.h for correct work?
Now I put png.h in %GOPATH%/src/github.com/go-vgo

But `robotgo.FindBitmap` dont work correct? the sample for [bitmap](https://github.com/go-vgo/robotgo#bitmap) work like this:
`... &{0x2a9690 30 40 120 32 4 [3 66 192 0 0 0]}
FindBitmap------ 1 1`

**Comment by vCaesar** [comment]
[This is a problem](https://github.com/go-vgo/robotgo/issues/29),when RGB>1 or <1,He can not find .May be fixed or add other function in 0.50.0

**Comment by AndersonTaylor** [comment]
I had a similar problem with the example for ```robotgo.FindBitmap``` returning:

```
... &{0x5818000 60 80 256 32 4 [0 0 0 0 0 0]}
FindBitmap------ 1 1
```
but mine was on Mac with libpng installed via brew.
Same result with and without an external monitor FWIW.

**Comment by vCaesar** [comment]
I see,This is a problem.
