### ISSUE TITLE
Drag mouse calling move mouse functions?

### ISSUE THREAD

**Issue by singh-ashish** [go-vgo/robotgo#331]
HI Team,

Thanks for creating this great library! I have a use case where drag mouse is not working on Linux Desktops.
Looking at the code  is the below call to move mouse function right from within drag mouse? ( I may be wrong :) )

https://github.com/go-vgo/robotgo/blob/e7f198aaf82284103f055d9d391b1ffc8a0c1c4e/mouse/mouse_c.h#L143

**Comment by vcaesar** [comment]
Use the `DragSmooth()`, drag is drop API now.
