### ISSUE TITLE
can we bypass this printing of key toggled?

### ISSUE THREAD

**Issue by girish946** [go-vgo/robotgo#34]
[str := C.aKeyToggle(ckey, cadown, camkey, camkeyt)](https://github.com/go-vgo/robotgo/blob/master/robotgo.go#L450)
I'm trying to hold down keys and when I do so it prints some data on the console.
as I'm already logging things. it just disturbs the log messages. 
so my question is it being printed deliberately for  some purpose or. can we bypass this printing?

**Comment by vCaesar** [comment]
Ok,I will Think about or change it.
