### ISSUE TITLE
Fail safe option

### ISSUE THREAD

**Issue by b1twe1ser** [go-vgo/robotgo#345]
I don't know if I missed it or if there is just no fail safe option but maybe you can consider implementing one, perhaps similar to the one in pyautogui. If I simply missed it, please let me know. Thank you 🙂

**Comment by richmailYT** [comment]
you can make your own, something like this
```
x, y := robotgo.GetMousePos()
//this check if the mouse is in the upper left corner
//if not, click
if x > 21 && y > 21 {
	time.Sleep(time.Duration(delay) * time.Millisecond)
	robotgo.Click(button, true)
} else {
        //if the user if trying to quit, stop by returning (this is using in a forever loop)
	return
}
```
