### ISSUE TITLE
键盘事件问题

### ISSUE THREAD

**Issue by yjbdsky** [go-vgo/robotgo#36]
1，按键事件监听，如何取消原按键动作，比如代码写上，比如要用A替换K时，当键盘按下K，达到键盘的实际输入是A，原来的K被取消
2，F1,ESC,小键盘这些如果操作？

**Comment by vCaesar** [comment]
1.Please show the code,Maybe you need to stop Event api,I will add it.
2.Not yet supported now,I will add it in 0.50.0

**Comment by yjbdsky** [comment]
thks!  ,非常感谢！
keve := robotgo.AddEvent("a")
	if keve == 0 {
		fmt.Println("you press...", "a", "but change to k")
		//I want to sotp a ,only send k key!
		robotgo.KeyTap("k")
	}
1, I want to sotp a ,only send k key!，我想把A键的动作取消。
2,  why print when mouse down? 为什么我按下鼠标时(没有按a)，也会打印提示？

**Comment by vCaesar** [comment]
Some debug printf is not clear,I clear some printf.

**Comment by vCaesar** [comment]
@yjbdsky I fix when you click mouse down print.Please update and test.

**Comment by yjbdsky** [comment]
I want use this package to change war3 skill key ，so need stop a, send k  ^_^

**Comment by yjbdsky** [comment]
Thank you very much ^_^

**Comment by vCaesar** [comment]
Ok,I will add "F1,ESC" and other in 0.50.0

**Comment by yjbdsky** [comment]
ok，I will  test it

**Comment by yjbdsky** [comment]
I test it 。
the left mouse button down is fixed.
but right mouse button is same problem.

**Comment by vCaesar** [comment]
I will use a mouse test it.

**Comment by vCaesar** [comment]
@yjbdsky In Mac have no problem, In Windows have some problem.

**Comment by vCaesar** [comment]
@yjbdsky I will test Ubuntu and fix it.

**Comment by yjbdsky** [comment]
en,I test in Windows

**Comment by vCaesar** [comment]
I fix it and test in Mac,Windows,Ubuntu.

**Comment by yjbdsky** [comment]
Thank you very much,is fixed. ^_^

**Comment by vCaesar** [comment]
^_^
