### ISSUE TITLE
Windows 10 error -- Application was unable to start correctly.

### ISSUE THREAD

**Issue by drrob1** [go-vgo/robotgo#360]
I compiled this program on Ubuntu 20.04 and Windows 10.  It works on Ubuntu, but on Windows 10 (fully updated to 21H1) I get:
"The application was unable to start correctly 0xc000 007b.  Click OK to close the application."

- Robotgo version (or commit ref):  https://github.com/go-vgo/robotgo/commit/6257bc4be945ebf3ff1f9f0bf8f109f63b543b45
- Go version:  1.16.7
- Gcc version: Msys2, latest version
- Operating system and bit: Windows 10 64 bit, 21H1
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):  
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant -- I don't see an example there
- Provide example code:

```Go
package main

import (
	"flag"
	"fmt"
	"github.com/go-vgo/robotgo"
	"os"
	"runtime"
	"time"
)

func main() {
	mousex, mousey := robotgo.GetMousePos()
	fmt.Println(" mouseX (col) =", mousex, "and mousey (row) =", mousey)

	fmt.Println()
	fmt.Println(" Will read and report mouse position in 10 seconds.")
	time.Sleep(10 * time.Second)
	finalMouseX, finalMouseY := robotgo.GetMousePos()
	fmt.Println(" Final mouse x =", finalMouseX, "and final mouse y =", finalMouseY)
	fmt.Println(" Final row =", finalMouseY, "and final column =", finalMouseX)

	robotgo.MoveMouse(mousex, mousey)

	fmt.Println()
} // main in robot.go
```
- Log gist:

## Description
"The application was unable to start correctly 0xc000 007b.  Click OK to close the application."

The program won't start on Windows 10 64-bit, but does on Ubuntu 20.04

**Comment by vcaesar** [comment]
Are you see #357 and other, or install and compiled the C depend.

**Comment by drrob1** [comment]
using the -a flag made no difference
I am using the MinGw64.  When I do gcc -v I get gcc version 10.2.0 (rev10, built by msys2 project)
I don't know what else to do
