### ISSUE TITLE
Running ok on CENTOS ,  but cross compiling to windows get errors

### ISSUE THREAD

**Issue by gujunyan** [go-vgo/robotgo#361]
GOOS=windows GOARCH=amd64 go build ./main.go 
# github.com/go-vgo/robotgo
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:30:24: undefined: hook.Event
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:31:9: undefined: hook.Start
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:36:2: undefined: hook.End
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:41:19: undefined: hook.Event
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:42:9: undefined: hook.Start
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:47:2: undefined: hook.End
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:52:2: undefined: hook.StopEvent
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:56:31: undefined: hook.Event
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:57:9: undefined: hook.Process
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:61:64: undefined: hook.Event
/root/go/pkg/mod/github.com/go-vgo/robotgo@v0.99.4/hook.go:57:9: too many errors

**Comment by vcaesar** [comment]
Are you see #343 and #228? You should install depend and set the CXX.

**Comment by pokitpeng** [comment]
try this cmd，when I enable CGO，it works !
`GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build ./main.go`
