### ISSUE TITLE
fatal error: event/goEvent.h: No such file or directory

### ISSUE THREAD

**Issue by maikoulin** [go-vgo/robotgo#369]
![图片](https://user-images.githubusercontent.com/9984908/134478523-c2fd2ba1-c316-4b16-8505-497764439c28.png)

# github.com/robotn/gohook
vendor\github.com\robotn\gohook\hook.go:22:27: fatal error: event/goEvent.h: No such file or directory
 #include "event/goEvent.h"
                           ^
compilation terminated

**Comment by vcaesar** [comment]
This is `go mod vendor` problem, golang #26366.

**Comment by weitzj** [comment]
I guess another fix would be to introduce `dummy.go` files with empty imports with the "C" CGO capture, i.e. "_ ...." so that go mod vendor will keep the C-Headers.

See for example the fix here how it is done:  https://github.com/wasmerio/wasmer-go/pull/197
