### ISSUE TITLE
C:\Users\Syatsuu\sdk\go1.17\pkg\tool\windows_amd64\link.exe: running g++ failed: exit status 1

### ISSUE THREAD

**Issue by Sya-tsuu** [go-vgo/robotgo#383]
- Robotgo version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

```
- Log gist:

## Description

...

**Comment by Sya-tsuu** [comment]
# excekWorker/sya
C:\Users\Syatsuu\sdk\go1.17\pkg\tool\windows_amd64\link.exe: running g++ failed: exit status 1
C:/Users/Syatsuu/sdk/go1.17/bin/pkg/mod/github.com/andlabs/ui@v0.0.0-20200610043537-70a69d6ae31e/libui_windows_amd64.a(init.cpp.obj): In function `DllMain':
C:/projects/libui/windows/init.cpp:170: multiple definition of `DllMain'
C:\Users\Syatsuu\AppData\Local\Temp\go-link-1268316365\000047.o:C:/Users/Syatsuu/sdk/go1.17/bin/pkg/mod/github.com/robotn/gohook@v0.31.2/hook/windows/properties_c.h:192: first defined here
collect2.exe: error: ld returned 1 exit status

**Comment by vcaesar** [comment]
The `UI and hook` have some repetition C defined, you can try other UI package.

**Comment by vcaesar** [comment]
You can use beta version, And maybe I will update hook API.
