### ISSUE TITLE
hook_run [1329]: Accessibility API is disabled!

### ISSUE THREAD

**Issue by metalwood** [go-vgo/robotgo#39]
- Robotgo version (or commit ref): latest
- Go version: go1.7.3 darwin/amd64
- Gcc version:Apple LLVM version 8.0.0 (clang-800.0.42.1)
- Operating system and bit:OS X El Capitan
- Provide example code: 
same as event demo
https://github.com/go-vgo/robotgo#event

- Log gist:

hook_run [1329]: Accessibility API is disabled!
Failed to enable access for assistive devices. (0X40)hook_run [1329]: Accessibility API is disabled!
Failed to enable access for assistive devices. (0X40)

**Comment by vCaesar** [comment]
@metalwood Must be allowed Accessibility api,please search,It's that easy!

**Comment by metalwood** [comment]
有没有QQ群？你是说在Mac的系统配置里允许当前程序操作系统吗？我见过不需要权限和系统配置白名单（只需要重启系统）就可以监听键盘事件的Mac程序。

**Comment by vCaesar** [comment]
@metalwood  Yep,This is global listen, and The window handle need this too.Maybe I will create a QQ group
