### ISSUE TITLE
Cannot get screen resolution under Win10 system

### ISSUE THREAD

**Issue by Core2002** [go-vgo/robotgo#393]
Cannot get screen resolution under Windows10 system
Version: github.com/go-vgo/robotgo v0.100.6
Image：[![IDWyb8.png](https://z3.ax1x.com/2021/11/12/IDWyb8.png)](https://imgtu.com/i/IDWyb8)

**Comment by vcaesar** [comment]
Use the `robotgo.GetScaleSize()`.

**Comment by Core2002** [comment]
# The problem is still not solved 
> image: [![IsVtfK.png](https://z3.ax1x.com/2021/11/13/IsVtfK.png)](https://imgtu.com/i/IsVtfK)

**Comment by vcaesar** [comment]
I will test it.

**Comment by vcaesar** [comment]
The window10 have new API, I updated it. And the default value will be made scaled in tests is completed.
