### ISSUE TITLE
Smooth Scrolling using robotgo

### ISSUE THREAD

**Issue by ravasan** [go-vgo/robotgo#395]
- Robotgo version (or commit ref): 0.100.6
- Go version: go version go1.17 darwin/arm64
- Gcc version: Apple clang version 12.0.5 (clang-1205.0.22.9)
- Operating system and bit: Macos v12.0.1(Monterey)
- Resolution: 2560 x 1600
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant
- Provide example code:

```Go
for True {
      robotgo.ScrollMouse(1, "down")
      robotgo.MilliSleep(1000)
}
```
- Log gist: 

## Description

Hi, I was trying to get a terminal app to smoothly scroll but can't figure out a way to do it. So I was wondering if there was a way to smoothly scroll hidden somewhere in the robot. I've tried using the above while loop but this is not "smooth". It is a noticeable and jagged way to scroll. Is there a way to reduce how much a "1" can scroll?

Or is there a way to scroll as we do in browsers(scroll by n pixels for some n, instead of "clicks") using which we could emulate smooth scrolling? Any idea on what we need to do to get smooth scroll to work(Do we need to implement something like this: https://en.wikipedia.org/wiki/Smoothstep)?

**Comment by vcaesar** [comment]
Use:
```go
for {
    robotgo.Scroll(10, -10)
    robotgo.MilliSleep(200)
}
```
This function is seem "smooth".

**Comment by vcaesar** [comment]
Or you can use the new function ```robotgo.ScrollSmooth(-1, 10)``` scroll 10 times.
