### ISSUE TITLE
Click function does not work properly on Windows 10

### ISSUE THREAD

**Issue by Core2002** [go-vgo/robotgo#399]
> Version 0.100.7
[![If0yYF.png](https://z3.ax1x.com/2021/11/16/If0yYF.png)](https://imgtu.com/i/If0yYF)

**Comment by Core2002** [comment]
> 版本	Windows 10 家庭中文版
> 版本号	21H1
> 安装日期	‎2021/‎10/‎28
> 操作系统内部版本	19043.1348
> 体验	Windows Feature Experience Pack 120.2212.3920.0
>

**Comment by vcaesar** [comment]
Fixed, and some other function like this bug? There will be released when the more test is completed.

**Comment by vcaesar** [comment]
Maybe GetMousePos() like this too, and are you test on the windows7?

**Comment by vcaesar** [comment]
You should use the `robotgo.MouseSleep = 100` first.

**Comment by okridgway** [comment]
I'm having this issue too.

**Comment by okridgway** [comment]
@vcaesar

**Comment by Core2002** [comment]
This bug still exists on win11

**Comment by vcaesar** [comment]
You can use `robotgo.ScaleF()`.
