### ISSUE TITLE
Windows you can use w32 instead of cgo....

### ISSUE THREAD

**Issue by SaturnsVoid** [go-vgo/robotgo#4]
You can load windows API for all of the work you are doing for windows. This would make it more Pure-Go.

Check out github.com/AllenDang/w32 its a great package with almost everything.

**Comment by vCaesar** [comment]
Ok,Thank you for your suggestion,I will add it in future

**Comment by vCaesar** [comment]
But in linux and Mac OS X can't find someone,so don't add it.
