### ISSUE TITLE
possition of mouse

### ISSUE THREAD

**Issue by richmailYT** [go-vgo/robotgo#418]
1. Please **speak English**, this is the language everybody of us can speak and write.
2. Please take a moment to **search** that an issue **doesn't already exist**.
3. Please make sure `Golang, GCC` is installed correctly before installing RobotGo.
4. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-vgo/robotgo
5. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Robotgo version (or commit ref): 0.100.9
- Go version: 1.17.3
- Gcc version: 12.0.0
- Operating system and bit: 64 bit, MacOS Catalina 10.15.7
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant
How to get position of mouse

...

**Comment by vcaesar** [comment]
You should read README.md and godoc, issues is not docs, `robotgo.GetMousePos()`
