### ISSUE TITLE
mac 上鼠标点击怎么没用？，没有任何响应 。求教

### ISSUE THREAD

**Issue by tx991020** [go-vgo/robotgo#419]
package main

import (
	"github.com/go-vgo/robotgo"
	"time"
)

func main() {
	

	robotgo.MoveMouse(0, 0)
	robotgo.Click("right", true)

	time.Sleep(time.Second*3)

}

**Comment by vcaesar** [comment]
Closing is due to duplicate ( #277 ) and non-standard.
