### ISSUE TITLE
 Why is the mouse click useless on mac? , No response Please read carefully before closing, I think this is a bug

### ISSUE THREAD

**Issue by tx991020** [go-vgo/robotgo#421]
Please read carefully before closing, I think this is a bug![image](https://user-images.githubusercontent.com/12123206/145921257-f05844a0-0e3f-4f7e-b4fa-87b22a342ad6.png)

The same command line, the same system preferences, rust can be, my current problem mouse control is not responding, not screen recording

macos 10.15.5
clang Homebrew clang version 13.0.0
Target: x86_64-apple-darwin19.5.0
go version go1.16.3 darwin/amd64

```go
package main

import (
"github.com/go-vgo/robotgo"
"time"
)

func main() {

robotgo.MoveMouse(0, 0)
robotgo.Click("right", true)

time.Sleep(time.Second*3)
}

use enigo::{Enigo, KeyboardControllable, MouseButton, MouseControllable};

fn main() {
    let mut enigo = Enigo::new();

    enigo.mouse_move_to(0, 0);
    enigo.mouse_click(MouseButton::Left);
    enigo.key_sequence_parse("{+CTRL}a{-CTRL}{+SHIFT}Hello World{-SHIFT}");
}
```

**Comment by tx991020** [comment]
I request again, please read the question first, don’t close it before reading it。my problem is that I can't control the mouse, I can record the screen. I have confirmed many times and the computer's system preferences are fully opened.


Look at the following code to record the screen, but the mouse cannot be controlled

![image](https://user-images.githubusercontent.com/12123206/145923117-c4d0824d-2bb0-4151-821c-f1ab4f6ea029.png)

**Comment by vcaesar** [comment]
But there can't be reproduce, you should `Sleep` before `Click`, you can try 
```go 
robotgo.MouseSleep = 100
robotgo.Move(10, 10)
robotgo.Click()
```
If this problem persists, please tell me how to reproduce it.

**Comment by tx991020** [comment]
I found the reason, and found that it needs to be executed in the terminal, but there is no response when executed in item2, although both have opened system permissions

**Comment by vcaesar** [comment]
This is work in my iterm2, check or update your iterm2.
