### ISSUE TITLE
 shift not woking

### ISSUE THREAD

**Issue by wangxudong123** [go-vgo/robotgo#423]
- Robotgo version (or commit ref):
- Go version:0.100.10
- mac os 12.0.1

![image](https://user-images.githubusercontent.com/20228139/147118381-495430dc-d8d2-4aea-8fa6-7d694bef554f.png)

**Comment by 1143201754** [comment]
Yes, I have the same problem

My system is windows 10

**Comment by alchem1ster** [comment]
Use `hook.KeyHold` instead

**Comment by wangxudong123** [comment]
> Use `hook.KeyHold` instead

Thank you. I will try this method in my spare time
