### ISSUE TITLE
Can I get the process ID or filename of current active window?

### ISSUE THREAD

**Issue by metalwood** [go-vgo/robotgo#43]
Some active window title is null, such like QQ under MacOS, so we don't know what application it is by GetTitle().
If not, could you add the new API GetActiveWindowProcessId() or GetActiveWindowProcessFilename()?

**Comment by vCaesar** [comment]
@metalwood  I will test GetTitle(),I have process ID APi in the local,But I'm gonna test it with get all Windows.

**Comment by vCaesar** [comment]
I see,I tested QQ have problem,other no problem.

**Comment by vCaesar** [comment]
@metalwood I add get process ID APi.
