### ISSUE TITLE
Installing RobotGo - invalid operation: geve == 0 (mismatched types bool and untyped int)

### ISSUE THREAD

**Issue by jacz24** [go-vgo/robotgo#433]
- Robotgo version (or commit ref): v0.100.10
- Go version: 1.17.6
- Gcc version: 10.3.0
- Operating system and bit: WIndows
- Resolution: 2160x1440
- Can you reproduce the bug:
  - [Y] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

go get github.com/go-vgo/robotgo

```
- Log gist:

go\pkg\mod\github.com\go-vgo\robotgo@v0.100.10\hook.go:98:14: invalid operation: geve == 0 (mismatched types bool and untyped int)

```

## Description

Seems the function in question is trying to return an int with: return geve == 0
But the function is clearly typed to only return a bool: func AddEvent(key string) bool {

I was able to get it to install by just commenting geve := hook.AddEvent(key) and change it to return to false
But I am unaware of what the consequence will be.

**Comment by vcaesar** [comment]
Keep the gohook version with go mod.

**Comment by vcaesar** [comment]
Or you can use robotgo v1.0.0-beta1.

**Comment by ivanskodje** [comment]
> Keep the gohook version with go mod.

Can you elaborate on this? I am having the same problems.

---

> Or you can use robotgo v1.0.0-beta1.

By trying to use the beta version `go get -u github.com/go-vgo/robotgo@v1.0.0-beta1` 
I get the following error when running the test-app: 

```
getpointer.go:7:2: no required module provides package github.com/go-vgo/robotgo: go.mod file not 
found in current directory or any parent directory; see 'go help modules'
```

**Comment by vcaesar** [comment]
You can edit go.mod, same with [bitmap](https://github.com/vcaesar/bitmap/blob/main/go.mod).

**Comment by wanderdevof** [comment]
Change `geve == 0` to `geve == false`

**Comment by FreemanFeng** [comment]
> Keep the gohook version with go mod.

could you pls. tell me which gohook version should be kept? thanks.

**Comment by xLeDocteurx** [comment]
go get -u github.com/go-vgo/robotgo@v1.0.0-beta1

worked for me. golang v 1.18
