### ISSUE TITLE
Sometimes "robotgo.ActivePID" fails to activate window 

### ISSUE THREAD

**Issue by aj3423** [go-vgo/robotgo#436]
- Robotgo version (or commit ref):  v1.0.0-beta1.0.20220112031049-0b2e9034b29b
- Go version: go1.17.1 linux/amd64
- Gcc version: x86_64-w64-mingw32-gcc 10-win32 20210110
- Operating system and bit: Kali Linux  cross-compile for Windows Server 2016
- Resolution: 1280 * 960
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
func main() {
	pids, _ := robotgo.FindIds("notepad")

	for _, pid := range pids {
		robotgo.ActivePID(pid)

		time.Sleep(1000 * time.Millisecond)

		title := robotgo.GetTitle(pid)
		fmt.Println("pid:", pid, "title:", title)

		time.Sleep(1000 * time.Millisecond)
	}
}

```
## Description
I expect the code to activate 3 "notepad" one by one, but only the first is activated, the other two only flashes on the task bar. 
The screenshot:
![robotgo](https://user-images.githubusercontent.com/4710875/149637150-5a933091-fb03-4db3-a49e-43dc141f5a0e.gif)

I thought maybe it's caused by cross-compiling, but I tried compile on *Windows10 + msys64 gcc (Rev10, Built by MSYS2 project) 10.2.0*, same problem. 

BTW, why the `GetTitle` returns "Mode Indicator" instead of "新建文本文档 - 记事本" as the title?
...

**Comment by visimulator** [comment]
first of all, thanks the author for providing so good tool robotgo!

I used your code and added the following code before printing the titles, it activated the three windows one by one, and worked well

title_dec, _ := simplifiedchinese.GBK.NewDecoder().String(title)  

if the title was not decoded,  it would print some unreadable chars but the words "Mode Indicator"

my env:
windows 10 pro x64 chinese edition, 
msys64 mingw-w64-x86_64-toolchain
golang 1.17.5
