### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [go-vgo/robotgo#45]
I would like to point out that identifiers like “[`__IOHOOK_H`](https://github.com/go-vgo/robotgo/blob/cfc16a18d1d0bfcceead6c679e6b99b06dcee68d/event/hook/iohook.h#L2 "Update candidate")” and “[`_MEvent`](https://github.com/go-vgo/robotgo/blob/c14451562b2931f46088500400068d605bfe4518/event/goEvent.h#L70 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by vCaesar** [comment]
Thank you for your suggestion,I will think about it.

**Comment by vcaesar** [comment]
Closing is due to can't updates.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
