### ISSUE TITLE
for { hwnd := robotgo.GetHandle() }  return 0？

### ISSUE THREAD

**Issue by appleatiger** [go-vgo/robotgo#46]
cannot get the handle。。。

**Comment by vCaesar** [comment]
You should give more information,I do not know in which system to reproduce it.

**Comment by appleatiger** [comment]
package main

import (
	"fmt"
	"time"
	"github.com/go-vgo/robotgo"
)


func main() {
	sum := 0
	for {
		sum++
		if sum > 99999999 {
			break
		} else {
			time.Sleep(5 * time.Second)
			mdata := robotgo.GetActive()
			fmt.Println("mdata--", mdata)
			hwnd := robotgo.GetHandle() //获取当前窗口hwnd
			fmt.Println("hwnd--", hwnd)
		}
	}
}
i can get mdata，but cannot get hwnd。

**Comment by vCaesar** [comment]
@appleatiger  "hwnd := robotgo.GetHandle()" and"
     for i := 0; i < 3; i++ {
		fhwnd := robotgo.GetHandle()
		Println("fhwnd---", fhwnd)
	}" is normal,but in this can't get hwnd,Maybe the runtime error or cgo bug,I will troubleshoot it.

**Comment by vCaesar** [comment]
you can use it in windows:
hwnd := mdata.HWnd  
fmt.Println("hwnd--", hwnd)

**Comment by appleatiger** [comment]
if use hwnd := mdata.HWnd,i can see a string like this :"&{6619242}",it cannot be used for "SetHandle(hwnd)"

**Comment by vCaesar** [comment]
hwnd := int(mdata.HWnd),Type conversion.

**Comment by appleatiger** [comment]
cannot convert mdata.HWnd (type robotgo._Ctype_HWND) to type int

**Comment by vCaesar** [comment]
I see,I use Windows test it,I use mac test it before this.

**Comment by vCaesar** [comment]
Because of golang not have Macro definition,Let me think about it.

**Comment by vCaesar** [comment]
Please try GetBHandle.

**Comment by appleatiger** [comment]
good job！
