### ISSUE TITLE
How to read and find an image using embed?

### ISSUE THREAD

**Issue by SirRFI** [go-vgo/robotgo#461]
- Robotgo version (or commit ref): `v0.100.10`
- Go version: `go1.17 windows/amd64`
- Gcc version: `gcc version 8.1.0 (x86_64-win32-seh-rev0, Built by MinGW-W64 project)`
- Operating system and bit: `Windows 10 64bit`
- Resolution: 1920x1080

## Description

How to read and find an image using `go:embed`?

I tried following:

1. As suggested in https://github.com/go-vgo/robotgo/issues/309
```go
//go:embed image.png
var image []byte

func main() {
	img, _, _ := image.Decode(bytes.NewReader(image))
	bit := robotgo.ImgToBitmap(img)
	x, y := robotgo.FindBitmap(bit)

	fmt.Println(x, y)
}
```
Does not build due to type mismatch:
> cannot use bit (type robotgo.Bitmap) as type robotgo._Ctype_MMBitmapRef in argument to robotgo.FindBitmap

---

2. 
```go
//go:embed image.png
var image string

func main() {
	img := robotgo.BitmapFromStr(image)
	x, y := robotgo.FindBitmap(img)
	
	fmt.Println(x, y)
}
```
Builds, but doesn't find given image on the screen (image's content seems to be loaded via embed):
> bitmap is not ready yet!
> -1 -1

---

3. 
```go
func main() {
	bit := robotgo.OpenBitmap("image.png")
	x, y := robotgo.FindBitmap(bit)
	
	fmt.Println(x, y)
}
```
This works, but doesn't use embed - just reads the same file from file system:
> 1502 12

---

4. I also wanted to try `v1.0.0-beta4`, but I can't find any function that would find given image on the screen. How to do that?

**Comment by vcaesar** [comment]
1. You should use `robotgo.ToCBitmap()`.
4. You should use `bitmap` package.

**Comment by SirRFI** [comment]
I tried following:
```go
package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"github.com/go-vgo/robotgo"
	"github.com/vcaesar/bitmap"
	"image"
)

//go:embed image.png
var icon []byte

func main() {
	img, _, _ := image.Decode(bytes.NewReader(icon))
	bm := robotgo.ImgToBitmap(img)
	cBm := robotgo.ToCBitmap(bm)
	x, y := bitmap.Find(cBm)
	fmt.Println(x, y)
}
```
Types now match, but the code crashes at `bitmap.Find` line with `exit status 0xc0000005`.
As far I can tell in debugger, lines prior the one that crashes work properly.

go version go1.17.6 windows/amd64
github.com/go-vgo/robotgo v1.0.0-beta4
github.com/vcaesar/bitmap v0.10.0-beta2.1

Can you provide working example in case I am doing something wrong? Can this be shortened?

Ps. What is `BitmapFromStr` for? I assumed that image's content can be passed as string.

**Comment by vcaesar** [comment]
There have some examples, but delete with the refactor, I will add it in bitmap package.

**Comment by SirRFI** [comment]
I can confirm that downgrading robotgo to beta3 no longer causes `bitmap.Find` to crash.

However, the snippet from previous comment still does not work - image is not found on the screen. When I replace it with filesystem version, it works:
```go
cBm := bitmap.Open("image.png")
x, y := bitmap.Find(cBm)
```

Let me know when embed example is available, so I'll test again.

**Comment by vcaesar** [comment]
The conversion process accuracy is lost, the bitmap.find() over-reliance on image accuracy, it is recommended to use `gcv`.

**Comment by SirRFI** [comment]
I understand that finding bitmap is more or less pixel-perfect comparison. For my use case it worked well so far.

The actual problem is that loading image from file system seems to behave differently than loading it using go:embed.

I noticed you updated both libraries. Here are test results:

<details>
<summary>robotgo v1.0.0-beta3 & bitmap v0.10.0-beta2</summary>

```go
package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"github.com/go-vgo/robotgo"
	"github.com/vcaesar/bitmap"
	"image"
)

//go:embed image.png
var embedImage []byte

func testUsingOpen() {
	cBm := bitmap.Open("image.png")
	x, y := bitmap.Find(cBm)
	fmt.Println("testUsingOpen", x, y)
}

func testUsingOpenC() {
	mmBitmapRef := bitmap.OpenC("image.png")
	cBm := bitmap.ToRobot(mmBitmapRef)
	x, y := bitmap.Find(cBm)
	fmt.Println("testUsingOpenC", x, y)
}

func testUsingEmbedDecode() {
	img, _, _ := image.Decode(bytes.NewReader(embedImage))
	bm := robotgo.ImgToBitmap(img)
	cBm := robotgo.ToCBitmap(bm)
	x, y := bitmap.Find(cBm)
	fmt.Println("testUsingEmbedDecode", x, y)
}

func main() {
	testUsingOpen()
	testUsingOpenC()
	testUsingEmbedDecode()
}
```

> go get github.com/go-vgo/robotgo@v1.0.0-beta4.1 github.com/vcaesar/bitmap@v0.10.0-beta3
> go run .
> testUsingOpen 1298 59
> testUsingOpenC 1298 59
> testUsingEmbedDecode -1 -1

</details>

<details>
<summary>robotgo v1.0.0-beta4.1 & bitmap v0.10.0-beta3</summary>

```go
package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"github.com/go-vgo/robotgo"
	"github.com/vcaesar/bitmap"
	"image"
)

//go:embed image.png
var embedImage []byte

func testUsingOpen() {
	cBm := bitmap.Open("image.png")
	x, y := bitmap.Find(cBm)
	fmt.Println("testUsingOpen", x, y)
}

func testUsingOpenC() {
	mmBitmapRef := bitmap.OpenC("image.png")
	cBm := bitmap.ToRobot(mmBitmapRef)
	x, y := bitmap.Find(cBm)
	fmt.Println("testUsingOpenC", x, y)
}

func testUsingEmbedDecode() {
	img, _, _ := image.Decode(bytes.NewReader(embedImage))
	bm := robotgo.ImgToBitmap(img)
	cBm := robotgo.ToCBitmap(bm)
	x, y := bitmap.Find(cBm)
	fmt.Println("testUsingEmbedDecode", x, y)
}

func testUsingEmbedByteToCBitmap() {
	cBm := robotgo.ByteToCBitmap(embedImage)
	x, y := bitmap.Find(cBm)
	fmt.Println("testUsingEmbedByteToCBitmap", x, y)
}

func main() {
	testUsingOpen()
	testUsingOpenC()
	testUsingEmbedDecode()
	testUsingEmbedByteToCBitmap()
}
```

(everything is the same, just `testUsingEmbedByteToCBitmap` is added)

> go get github.com/go-vgo/robotgo@v1.0.0-beta3 github.com/vcaesar/bitmap@v0.10.0-beta2
> go run .
> testUsingOpen -1 -1
> testUsingOpenC -1 -1
> testUsingEmbedDecode -1 -1
> testUsingEmbedByteToCBitmap -1 -1

</details>

As you see, something broke in newer version.

I also tried bmp files - similar result for 24 and 32 bit, but 16 bit bmp just crashes.

**Comment by vcaesar** [comment]
I tested it in macos, but can't reproduce.

**Comment by SirRFI** [comment]
I have expanded my test to additional images. Images are in PNG format. Results are the same as previously:
* robotgo@v1.0.0-beta3 & bitmap@v0.10.0-beta2 - images are found, except when loaded via `go:embed`
* robotgo@v1.0.0-beta4.1 bitmap@v0.10.0-beta3 - images are not found
* robotgo@v1.0.0-beta5 bitmap@v0.10.0-beta3.1 - images are not found

All your examples are capturing part of the screenshot (A) first, then subset of it (B), then search then search the subset in the screenshot (search B in A), optionally saving them to filesystem beforehand. My tests instead already have image to be searched for (B), and the screenshot (A) is whatever is currently on the screen, live.

Can you run Windows in a VM and test it? What could affect the difference between versions, aside from the package's code?

**Comment by SirRFI** [comment]
On side note, it would be really helpful that both opening the image and finding it actually returned an error when something failed, rather than have some silent behavior in case of Open methods, and -1 -1 (which I think can be valid position for multi-monitor setup) in case of Find method.

**Comment by SirRFI** [comment]
I have opened separate issues for other concerns that came up during the discussion.

I also managed to find an image coming from go:embed. It does not work with `image.Decode` from `image` package, but it does with `image2.Decode`, or in this case `png.Decode`.
