### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by burque505** [go-vgo/robotgo#469]
- Robotgo version (or commit ref): 0.100.10
- Go version: 1.17.5
- Gcc version: gcc (Rev5, Built by MSYS2 project) 11.2.0
- Operating system and bit: Windows 10 64-bit
- Resolution: 1920X1068
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [X] Not relevant
- Provide example code:
`pkg\mod\github.com\go-vgo\robotgo@v0.100.10\hook.go:98:14: invalid operation: geve == 0 (mismatched types bool and untyped int)`
```Go

```
- Log gist:

## Description
Cannot install correctly, although files exist in proper folders. Running 'go get -u github.com/go-vgo/robotgo' gives the following error:
`pkg\mod\github.com\go-vgo\robotgo@v0.100.10\hook.go:98:14: invalid operation: geve == 0 (mismatched types bool and untyped int)`

...

**Comment by oktaysenkan** [comment]
Duplication of #433

**Comment by burque505** [comment]
Thanks, @oktaysenkan.
