### ISSUE TITLE
Implement shift + click

### ISSUE THREAD

**Issue by oktaysenkan** [go-vgo/robotgo#470]
How the implement `shift` + `click`?

```go
robot.KeyDown("shift")
robot.MilliSleep(500)
robot.Click("left")
robot.MilliSleep(500)
robot.KeyUp("shift")
```

<img width="366" alt="Screen Shot 2022-02-15 at 8 39 32 AM" src="https://user-images.githubusercontent.com/42527467/153999503-96a6e62e-960e-48eb-84d6-65356f6ad230.png">

**[Playground](https://me48c.csb.app/)**

**Comment by vcaesar** [comment]
What's your os? I optimized this code.

**Comment by oktaysenkan** [comment]
Windows

**Comment by vcaesar** [comment]
Closed because of I test it on many os, and can't reproduce it (beta5).
