### ISSUE TITLE
Error on go get -u (invalid operation: geve == 0 (mismatched types bool and untyped int)

### ISSUE THREAD

**Issue by Brunoquindeler** [go-vgo/robotgo#477]
- Robotgo version (or commit ref): v0.100.10
- Go version: go1.17.7 windows/amd64
- Gcc version: 11.2.0
- Operating system and bit: Windows 64x
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [x] No
  - [ ] Not relevant

- Log gist:

## Description
PS C:\Users\bruno\OneDrive\Documentos\golang\robot> go get -u github.com/go-vgo/robotgo
go: downloading github.com/stretchr/testify v1.7.0
# github.com/go-vgo/robotgo
..\..\..\..\go\pkg\mod\github.com\go-vgo\robotgo@v0.100.10\hook.go:98:14: invalid operation: geve == 0 (mismatched types bool and untyped int)
...

**Comment by Brunoquindeler** [comment]
Sorry, I get an old release, it's fix on  v1.0.0-beta4.1

**Comment by vcaesar** [comment]
Closing is due to duplicate ( #433, #469). You should search issue first.

**Comment by Brunoquindeler** [comment]
Sorry, I get an old release, it's fix on  v1.0.0-beta4.1
