### ISSUE TITLE
left angle bracket replaced with right when typed

### ISSUE THREAD

**Issue by Zytekaron** [go-vgo/robotgo#493]
- Robotgo version: v0.100.0.1189, MT. Baker!
- Go version: go1.18 linux/amd64
- Gcc version: 11.2.0
- Operating system and bit: Arch Linux x86_64
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant

```go
package main

import "github.com/go-vgo/robotgo"

func main() {
	robotgo.TypeStr("<>") // types '>>'
}
```

## Description

When attempting to type the left angle bracket (aka less than) character, it is replaced with the right angle bracket. I'm not aware of any other instances of this bug; other bracket types work as expected.

**Comment by vcaesar** [comment]
This is should be a bug of x11, I fixed it.
