### ISSUE TITLE
TypeString Bug 

### ISSUE THREAD

**Issue by ThereWeGo** [go-vgo/robotgo#50]
今天新装的系统 ，环境版本都是最新的，主要TypeString存在问题
1. TypeString（str） str首字母必须大写， 否则无限输出第一个字母
2. TypeString 不输出中文

e.g.
`robotgo.TypeString("hello xxx") // hhhhhhhhhhhhhhhhh endless
robotgo.TypeString("E水电费水电费") // output: E without chinese`

**Comment by vCaesar** [comment]
The first question did not recur in mac, what Operating System are you using? Utf-8 is not yet supported.

**Comment by zeazen** [comment]
OS：Linux 4.4.0-3-deepin-amd64  , the os base on ubuntu or debian
is there a plan to support UTF-8, recently?

**Comment by vCaesar** [comment]
Yep, it's in the plan.

**Comment by vCaesar** [comment]
The first question did not recur on my Ubuntu 15.04, there may be some system version of the problem.

**Comment by zeazen** [comment]
many thanks to you

**Comment by zeazen** [comment]
what can i do to support UTF-8, if i want to join the job.

**Comment by vCaesar** [comment]
Fork -> Patch -> Push -> Test -> Pull Request.If i want to join the job, give me a PR, thank you.

**Comment by zeazen** [comment]
i read the source:
```
void typeString(const char *str)
{
	while (*str != '\0') {
		tapUniKey(*str++);
	}
}
```
it seems not fit to type in UTF-8 character, like Chinese .

**Comment by zeazen** [comment]
may the repos "github.com/atotto/clipboard" can help solve this problem, i am using it to type UTF-8 character. :)

**Comment by vCaesar** [comment]
Thank you for your recommend. It 's busy in life now, wait for it, I solved it.

**Comment by ZengLeiPro** [comment]
It's easy to solve.
`import "github.com/atotto/clipboard"

clipboard.WriteAll(text_chinese)
robot.KeyTap("v", "command")`

**Comment by vCaesar** [comment]
Good, I will use it as a transitional plan.
