### ISSUE TITLE
GetPixelColor always return 000000 on Windows 10

### ISSUE THREAD

**Issue by ofabricio** [go-vgo/robotgo#501]
- Robotgo version (or commit ref): v1.0.0-beta5.2
- Go version: 1.18.1
- Gcc version: 11.2.0
- Operating system and bit: Windows 10, 64bits
- Resolution: 1920x1080
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
func main() {
    c := robotgo.GetPixelColor(500, 500)
    fmt.Println(c) // 000000
}
```
## Description

`GetPixelColor` always return `000000` on Windows 10, no matter the x, y value

**Comment by waynerQiu** [comment]
yes! and CaptureImg notwork too！

`c := robotgo.GetPixelColor(500, 500)
    fmt.Println(c) // 000000`

`imgLt := robotgo.CaptureImg(937, 57-*fix_top, 18, 19)
robotgo.Save(imgLt, "test.png") //empty png file(1kb)`

**Comment by jimqi** [comment]
Experiencing the same thing. CaptureScreen results in a black rectangle.
- Go version: 1.18.1
- Gcc version: 12.1.0
- Operating system and bit: Windows 11, 64bits
- Resolution: 2x 2560x1440

Trying out older builds the latest build that still had working screen capture for me was v1.0.0-beta3
