### ISSUE TITLE
cross-platform Build

### ISSUE THREAD

**Issue by khjde1207** [go-vgo/robotgo#51]
I am using Ubuntu.
Cross Compile

/github.com/go-vgo/robotgo$ GOOS=windows GOARCH=386 go build -o test.exe

Error message : 
can't load package: package github.com/go-vgo/robotgo: no buildable Go source files in /home/say/golang/gowork/src/github.com/go-vgo/robotgo

 Linux Cross Compile, What packages do I need ?

**Comment by vCaesar** [comment]
Because dependent on cgo and zlib/libpng, cross-platform compilation is difficult.

**Comment by khjde1207** [comment]
Thank you

**Comment by gedw99** [comment]
Try xgo . It solves this cross compile problem where you have to do cgo.

**Comment by Marahin** [comment]
@gedw99 xgo is cool but it still turns up with an error:
```
Checking for required docker image karalabe/xgo-latest... found.
Cross compiling git.3lab.re/marahin/artsh_helper_11...
Building locally git.3lab.re/marahin/artsh_helper_11...
Compiling for windows-4.0/amd64...
# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/io_c.h:4:0,
                 from ./bitmap/goBitmap.h:25,
                 from ../../../github.com/go-vgo/robotgo/robotgo.go:39:
./bitmap/../base/png_io_c.h:4:17: fatal error: png.h: No such file or directory
compilation terminated.
2017/07/18 13:33:43 Failed to cross compile package: exit status 2.
```

However locally it compiles just great. Any advises?

**Comment by gedw99** [comment]
actually i think the two non golang dependencies can be replaced with golang.
Have seen lots of code related to them the last few days floating around.

Is this something WE are interested in ? I can try to get the URLS to the golang packages.... But only if this is really wanted as i am pushed for time right now.

**Comment by Marahin** [comment]
@gedw99 I can definitely say for myself that it would make a lot of things easier, as I'm often required to compile programs for both macos and windows.

**Comment by gedw99** [comment]
anyone else though ?? 
@Caesar ?

**Comment by vCaesar** [comment]
Remove these two dependencies in the plan, but it takes time, busy in recent months, may move to another city to live.

**Comment by derek-razorfish** [comment]
+1 on removing windows dependencies and allowing linux/macos to build .exe files.

**Comment by Marahin** [comment]
I would love to see an update on this. 👍

**Comment by vcaesar** [comment]
Please see the [README.md](https://github.com/go-vgo/robotgo#crosscompiling).
