### ISSUE TITLE
Simultaneous processing of more than one keyboard key

### ISSUE THREAD

**Issue by Aivaki** [go-vgo/robotgo#517]
- Robotgo version (or commit ref): v1.00.0.1189
- Go version: go1.17 windows/amd64
- Gcc version: [TDM-GCC 10.3.0](https://jmeubank.github.io/tdm-gcc/articles/2021-05/10.3.0-release)
- Operating system and bit: Windows 11 x64
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
// this code illustrates the problem
hook.Register(hook.KeyHold, []string{}, func(e hook.Event) {
        key := e.Keycode
	switch key {
	    case 57:
	        fmt.Println("spacebar")
	    default:
		fmt.Println("pressed ", key)
	}
})
s := hook.Start()
<-hook.Process(s)
```

```Go
// or this (on the example with shift)
hook.Register(hook.KeyHold, []string{"shift"}, func(e hook.Event) {
         fmt.Println("shift")
})
s := hook.Start()
<-hook.Process(s)
```

## Description
The point is not even in this code, but in the fact that `hook.Register` does not have the necessary functionality.

I want to hold the spacebar and execute some code while pressing other keys.
I'm holding down the space bar, but when I press another key, that key overrides the space bar.

What can be done about it?

**Comment by zyxkad** [comment]
You should register `hook.KeyDown` and `hook.KeyUp` with a bool map of keycode.  
For example:
```golang
type KeyMap [0xffff]bool
func (m KeyMap)Get(keys ...string)(bool){
  for _, k := range keys {
    if !m[keycode.Keycode[k]] {
      return false
    }
  }
  return true
}
var keymap KeyMap // type of Event.Keycode is uint16
func updateKeys(){
  if keymap.Get("shift", "space") {
    // do sth...
  }
}

hook.Register(hook.KeyDown, nil, func(e hook.Event) {
  k := e.Keycode
  keymap[k] = true
  updateKeys()
})
hook.Register(hook.KeyUp, nil, func(e hook.Event) {
  k := e.Keycode
  keymap[k] = false
  updateKeys()
})
```

**Comment by Aivaki** [comment]
> 

Thank you, but this code doesn't work for me, or I don't understand something, although everything is extremely simple in it...

**Comment by Aivaki** [comment]
> You should register `hook.KeyDown` and `hook.KeyUp` with a bool map of keycode. For example:
> 
> ```go
> type KeyMap [0x10000]bool // type of Event.Keycode is uint16, the max value of uint16 is 0xffff
> func (m KeyMap)Get(keys ...string)(bool){
>   for _, k := range keys {
>     if !m[keycode.Keycode[k]] {
>       return false
>     }
>   }
>   return true
> }
> var keymap KeyMap
> func updateKeys(){
>   if keymap.Get("shift", "space") {
>     // do sth...
>   }
> }
> 
> hook.Register(hook.KeyDown, nil, func(e hook.Event) {
>   k := e.Keycode
>   keymap[k] = true
>   updateKeys()
> })
> hook.Register(hook.KeyUp, nil, func(e hook.Event) {
>   k := e.Keycode
>   keymap[k] = false
>   updateKeys()
> })
> ```

Have you checked the operability of this code?

**Comment by zyxkad** [comment]
> Have you checked the operability of this code?

No, I just gave an **idea** or example, I don't promise the code is valid or can work well

**Comment by Aivaki** [comment]
I implemented this code in my own way, but it didn't solve the problem

> > Have you checked the operability of this code?
> 
> No, I just gave an **idea** or example, I don't promise the code is valid or can work well

I implemented this code in my own way, but it didn't solve the problem

**Comment by Aivaki** [comment]
As far as I understand, the author is not going to fix it. I will have to create my own similar package from scratch
