### ISSUE TITLE
fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by qiuapeng921** [go-vgo/robotgo#525]
- Robotgo version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
package main

import (
	"github.com/go-vgo/robotgo"
)

func main() {
	robotgo.MouseSleep = 100

	robotgo.ScrollMouse(10, "up")
	robotgo.ScrollMouse(20, "right")

	robotgo.Scroll(0, -10)
	robotgo.Scroll(100, 0)

	robotgo.MilliSleep(100)
	robotgo.ScrollSmooth(-10, 6)
	// robotgo.ScrollRelative(10, -100)

	robotgo.Move(10, 20)
	robotgo.MoveRelative(0, -10)
	robotgo.DragSmooth(10, 10)

	robotgo.Click("wheelRight")
	robotgo.Click("left", true)
	robotgo.MoveSmooth(100, 200, 1.0, 10.0)

	robotgo.Toggle("left")
	robotgo.Toggle("left", "up")
}
```
- Log gist:

## Description
![image](https://user-images.githubusercontent.com/19791012/183268569-b5215e8c-3b8e-4ff0-8be1-d675a16b3dc1.png)

...

**Comment by FGadvancer** [comment]
You need install mingw-64 on your windows.https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/
<img width="307" alt="image" src="https://user-images.githubusercontent.com/46924906/189574409-1e83df7a-18f3-4f48-b9cd-c0b236e78a93.png">

**Comment by mardukbp** [comment]
Yes. Download the zip file on the tail of the red arrow, unzip it and move the directory mingw64 to C:
Then execute the following commands:

```
go env -w CC=C:\mingw64\bin\gcc
go env -w CXX=C:\mingw64\bin\g++
```

Now `go build` should run successfully.

All the credit goes to Carson on [SO](https://stackoverflow.com/a/72424179/3534491).
