### ISSUE TITLE
Error with Go version 1.19 in windows

### ISSUE THREAD

**Issue by nicearma** [go-vgo/robotgo#528]
I'm trying to compile the project, but i'm getting errors like: 

`go get  github.com/go-vgo/robotgo@latest`

And i got 

```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

If i try to use install 

`go install  github.com/go-vgo/robotgo@latest
`

And again

```

go: downloading github.com/go-vgo/robotgo v0.100.10
go: downloading github.com/vcaesar/keycode v0.10.0
go: downloading github.com/lxn/win v0.0.0-20210218163916-a377121e959e
go: downloading github.com/robotn/gohook v0.31.3
go: downloading github.com/vcaesar/tt v0.20.0
go: downloading github.com/vcaesar/imgo v0.30.0
go: downloading github.com/vcaesar/gops v0.21.3
go: downloading github.com/shirou/gopsutil v3.21.10+incompatible
go: downloading golang.org/x/image v0.0.0-20211028202545-6944b10bf410
go: downloading golang.org/x/sys v0.0.0-20211123173158-ef496fb156ab
go: downloading github.com/StackExchange/wmi v1.2.1
go: downloading github.com/go-ole/go-ole v1.2.6
**package github.com/go-vgo/robotgo is not a main package**
```

It seem that Go deprecated the Get command and i think that install search for i file that is not there

PD: i'm not want to work direct with GO, i was trying to install robotn and i got the same errors that i describe before, so i switch to the commend line in GO

**Comment by zyxkad** [comment]
You must do `go mod init` to init the `go.mod` file before if you want to use `go get` to get a module

**Comment by zyxkad** [comment]
This is a **question**, not a problem or issue, this issue should close

**Comment by zyxkad** [comment]
> If i try to use install
> `go install github.com/go-vgo/robotgo@latest`

`go install` is use for building package as ***executable binary files***, generally not use for get package
