### ISSUE TITLE
Mouse move not correctly on win10 when display scale factor set to 150%

### ISSUE THREAD

**Issue by FreemanFeng** [go-vgo/robotgo#544]
1. Please **speak English (English only)**, this is the language everybody of us can speak and write.
2. Please take a moment to **search** that an issue **doesn't already exist**.
3. Please make sure `Golang, GCC` is installed correctly before installing RobotGo.

5. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Robotgo version (or commit ref): V1.0.0-beta5.3
- Go version: 1.19
- Gcc version: 11.2
- Operating system and bit: win10 64bits
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  Yes
- Provide example code:
  JUST CALL robotgo.MoveClick(x, y)

```Go

```
- Log gist:

## Description
My laptop resolution is 1920x1080, I scale the display factor to 150%, I am not sure whether this cause robotgo not handling correctly.
I use pyautogo to move to the same point (x, y) and click, it works!
So I guest that robotgo may need to compare with pyautogo implementation to find the difference. thanks.
...

**Comment by FreemanFeng** [comment]
should do conversion below for windows gui:
f := robotgo.ScaleF()
robotgo.MoveClick(int(float64(x)/f), int(float64(y)/f))

**Comment by zzp198** [comment]
Indeed, pyautogui has taken into consideration the need to directly use real coordinates. Robotgo relies on the advantages of the Go language, but coordinate conversion still requires self calculation.
