### ISSUE TITLE
Event example: free(): invalid size: 0x0000000001d43ab0

### ISSUE THREAD

**Issue by rahilwazir** [go-vgo/robotgo#55]
- Robotgo version (or commit ref): master (https://github.com/go-vgo/robotgo/commit/13d76e7e8b53686a37ee48b81f09cc434c9b8842)
- Go version: 1.7.4
- Gcc version: 6.3.1
- Operating system and bit: Fedora 25 64-bit
- Can you reproduce the bug at [Example](https://github.com/go-vgo/robotgo/blob/master/example/main.go):
  - [ ] Yes (provide example code)
  - [x] No
  - [ ] Not relevant
- Provide example code: 
    ```Go

    ```
- Log gist: https://gist.github.com/rahilwazir/1fbccb0e55f3b6536895fb09232c6460

## Description

Getting error when pressing <kbd>k</kbd> in the [Event](https://github.com/go-vgo/robotgo#event) example.

The packages were different than mentioned for Ubuntu in [README.md](https://github.com/go-vgo/robotgo#ubuntu)

Installed missing packages:

```
$ sudo dnf install libxkbcommon-devel libXtst-devel libxkbcommon-x11-devel xorg-x11-xkb-utils-devel
```

**Comment by vCaesar** [comment]
I will install Fedora and test it.
