### ISSUE TITLE
unexpected reloc for dynamic symbol _NSConcreteGlobalBlock

### ISSUE THREAD

**Issue by zhangshanhai** [go-vgo/robotgo#58]
# command-line-arguments
github.com/go-vgo/robotgo(__DATA/__const): unexpected reloc for dynamic symbol _NSConcreteGlobalBlock

**Comment by vCaesar** [comment]
Please provide your system information and what have you done?

**Comment by zhangshanhai** [comment]
go run -ldflags -s main.go

add  -ldflags -s，is ok。



go 1.7
