### ISSUE TITLE
[ERROR] cross compile from amd64_linux to aarch64_linux

### ISSUE THREAD

**Issue by 26n119e** [go-vgo/robotgo#587]
go.mod

```
module tvbox

go 1.19

require (
        github.com/go-vgo/robotgo v1.0.0-rc1
        github.com/gorilla/websocket v1.5.0
)

require (
        github.com/gen2brain/shm v0.0.0-20221026125803-c33c9e32b1c8 // indirect
        github.com/go-ole/go-ole v1.2.6 // indirect
        github.com/jezek/xgb v1.1.0 // indirect
        github.com/kbinani/screenshot v0.0.0-20210720154843-7d3a670d8329 // indirect
        github.com/lufia/plan9stats v0.0.0-20230326075908-cb1d2100619a // indirect
        github.com/lxn/win v0.0.0-20210218163916-a377121e959e // indirect
        github.com/otiai10/gosseract v2.2.1+incompatible // indirect
        github.com/power-devops/perfstat v0.0.0-20221212215047-62379fc7944b // indirect
        github.com/robotn/xgb v0.0.0-20190912153532-2cb92d044934 // indirect
        github.com/robotn/xgbutil v0.0.0-20190912154524-c861d6f87770 // indirect
        github.com/shirou/gopsutil/v3 v3.23.4 // indirect
        github.com/shoenig/go-m1cpu v0.1.6 // indirect
        github.com/tklauser/go-sysconf v0.3.11 // indirect
        github.com/tklauser/numcpus v0.6.0 // indirect
        github.com/vcaesar/gops v0.30.1 // indirect
        github.com/vcaesar/imgo v0.30.2 // indirect
        github.com/vcaesar/keycode v0.10.0 // indirect
        github.com/vcaesar/tt v0.20.0 // indirect
        github.com/yusufpapurcu/wmi v1.2.3 // indirect
        golang.org/x/image v0.7.0 // indirect
        golang.org/x/sys v0.8.0 // indirect
)
```

############################################################

I have some problems, when I try to compile from amd64_linux to aarch64_linux.

I use this command to compile the code:
CGO_ENABLE=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build main.go

but result is:
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/img.go:92:40: undefined: Bitmap
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/img.go:107:38: undefined: Bitmap
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/img.go:137:20: undefined: Bitmap
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/screen.go:26:28: undefined: Rect
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/robotgo_fn_v1.go:9:2: undefined: Move
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/robotgo_fn_v1.go:17:2: undefined: Toggle
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/robotgo_fn_v1.go:18:2: undefined: MilliSleep
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/robotgo_fn_v1.go:20:2: undefined: MoveSmooth
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/robotgo_fn_v1.go:21:2: undefined: Toggle
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/robotgo_fn_v1.go:29:9: undefined: MoveSmooth
../../pkg/mod/github.com/go-vgo/robotgo@v1.0.0-rc1/robotgo_fn_v1.go:29:9: too many errors

when I use this command  to compile, it's normal.
go build main.go

how can I reslove this problem?

**Comment by wilon** [comment]
Just try this https://github.com/go-vgo/robotgo/issues/552#issuecomment-1664935423
