### ISSUE TITLE
没办法运行，请问是什么问题

### ISSUE THREAD

**Issue by zpwd63** [go-vgo/robotgo#59]
在window10环境下运行，已经按照安装说明配置了E:\OpenSources\Mingw\bin 环境变量，但是还是报错
，请问如何解决？谢谢！
运行demo报错信息：
# command-line-arguments
github.com/go-vgo/robotgo(.text): relocation target png_create_write_struct not defined
github.com/go-vgo/robotgo(.text): relocation target png_set_longjmp_fn not defined
github.com/go-vgo/robotgo(.text): relocation target png_create_info_struct not defined
github.com/go-vgo/robotgo(.text): relocation target png_set_IHDR not defined
github.com/go-vgo/robotgo(.text): relocation target png_malloc not defined
github.com/go-vgo/robotgo(.text): relocation target png_malloc not defined
github.com/go-vgo/robotgo(.text): relocation target png_set_rows not defined
github.com/go-vgo/robotgo(.text): relocation target png_destroy_write_struct not defined
github.com/go-vgo/robotgo(.text): relocation target png_set_bgr not defined
github.com/go-vgo/robotgo(.text): relocation target png_destroy_write_struct not defined
github.com/go-vgo/robotgo(.text): relocation target png_free not defined
github.com/go-vgo/robotgo(.text): relocation target png_destroy_write_struct not defined
github.com/go-vgo/robotgo(.text): relocation target png_get_io_ptr not defined
github.com/go-vgo/robotgo(.text): relocation target png_malloc not defined
github.com/go-vgo/robotgo(.text): relocation target png_sig_cmp not defined
github.com/go-vgo/robotgo(.text): relocation target png_create_read_struct not defined
github.com/go-vgo/robotgo(.text): relocation target png_create_info_struct not defined
github.com/go-vgo/robotgo(.text): relocation target png_set_longjmp_fn not defined
github.com/go-vgo/robotgo(.text): relocation target png_init_io not defined
github.com/go-vgo/robotgo(.text): relocation target png_set_sig_bytes not defined
github.com/go-vgo/robotgo(.text): relocation target png_read_info not defined
E:\OpenSources\Go\pkg\tool\windows_amd64\link.exe: too many errors

**Comment by vCaesar** [comment]
This is the problem with libpng, I will test it again on my windows.

**Comment by vCaesar** [comment]
I tested on the Windows 10 + go1.8.3, there is no problem. If you are convinced there is a robotgo problem, please tell us precisely how we can reproduce the problem ourselves.
