### ISSUE TITLE
zlib.h: No such file or directory

### ISSUE THREAD

**Issue by lowking** [go-vgo/robotgo#591]
- Robotgo version (or commit ref): v0.100.10
- Go version: go1.20 darwin/amd64
- Gcc version: Apple clang version 14.0.0 (clang-1400.0.29.202)
- Operating system and bit: macOS 13.2 (22D49)
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:
- 
```Go
// Copyright 2016 The go-vgo Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// https://github.com/go-vgo/robotgo/blob/master/LICENSE
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
	// "go-vgo/robotgo"
)

func main() {
	ver := robotgo.GetVersion()
	fmt.Println("robotgo version is: ", ver)

	// Control the keyboard
	// key()

	// Control the mouse
	// mouse()

	// Read the screen
	// screen()

	// Bitmap and image processing
	// bitmap()

	// Global event listener
	// event()

	// Window Handle and progress
	// window()
}

```
- Log gist:

## Description
Compiling on macOS works fine, but cross-compiling to win results in errors
```
# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2,
                 from ./bitmap/goBitmap.h:17,
                 from ../Desktop/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/bitmap.go:24:
./bitmap/../base/zlib_util_c.h:2:10: fatal error: zlib.h: No such file or directory
    2 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
```
![image](https://github.com/go-vgo/robotgo/assets/33308659/aba95bb4-b1ba-40bb-87ed-85a9c61ffb5c)
I tried all the solutions in the issue, but nothing worked

**Comment by tfmeneses** [comment]
I'm getting the same error. What is the fix?

**Comment by tfmeneses** [comment]
I just solve in windows using TDM-GCG. Thks all

`
- Downloaded zlib [zlib.net](http://www.zlib.net/) && cd zlip path
- gcc -O3 -c *.c
- ar rcs libz.a *.o
- cp libz.a to C:\TDM-GCC-64\lib\
- cp zlib.h  && zconf.h to C:\TDM-GCC-64\include\
- updated the robotgo to v1.0.0-rc1
`
