### ISSUE TITLE
can not use robotgo on macOSSierra 10.12.5 + go1.8

### ISSUE THREAD

**Issue by alphajh** [go-vgo/robotgo#60]
I found robotgo can not compile on the macOS Sierra 10.12.5, I have used the 'brew install' command,I have installed the libpng and zlib,but it's not work  althoughI take two hours to fix it.

**Comment by vCaesar** [comment]
I tested on the mac os 10.12.5 + go1.8.3, there is no problem. If you are convinced there is a robotgo problem, please tell us precisely how we can reproduce the problem ourselves.

**Comment by vCaesar** [comment]
Maybe you [issues/39](https://github.com/go-vgo/robotgo/issues/39).

**Comment by alphajh** [comment]
thank your reply VCaesar,today I downloaded the go 1.8.3,and now my program compile success.
I can use robotgo in my mac again,it's very Happy to me.

but, I just find a new problem is : when I use 'robotgo.TypeString()', it will lost the last word, 
e.g.:  I use 'robotgo.TypeString("ls")', the result is 'l'

**Comment by vCaesar** [comment]
I think it is a matter of delay, please see [issues/52](https://github.com/go-vgo/robotgo/issues/52).
