### ISSUE TITLE
can robotgo  AddEvent for two or more keys  at the same time?

### ISSUE THREAD

**Issue by DehaiWang** [go-vgo/robotgo#61]
can robotgo  AddEvent for two or more keys  at the same time?
and every key has it's callback function ?

**Comment by vCaesar** [comment]
Please see [issues/21](https://github.com/go-vgo/robotgo/issues/21), I will think about it or add it in future.

**Comment by bonly** [comment]
yes, need that

**Comment by vcaesar** [comment]
I will update it or give me a PR.
