### ISSUE TITLE
Disable warning show

### ISSUE THREAD

**Issue by musicyin** [go-vgo/robotgo#620]
##My example code is as follows：
```Go
for true {
	robotgo.Move(1, 1)
	robotgo.Click("left")
	time.Sleep(25* time.Millisecond)
	robotgo.KeyTap("a", "ctrl")
	robotgo.TypeStr("TEST")
	time.Sleep(25* time.Millisecond)
	robotgo.Move(2, 2)
	robotgo.Click("left")
	time.Sleep(25* time.Millisecond)
}
```

## Description
The following warning will appear when running for a long time：
process_button_pressed [322]: Click count overflow detected!
...

## Info
- Robotgo version (or commit ref): 1.0.0-rc2.1
- Go version:go1.21.2 windows/amd64
- Gcc version: x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0
- Operating system and bit: Windows 10 64 bit
- Resolution: 1920x1080

**Comment by vcaesar** [comment]
This log is in gohook not robot.
