### ISSUE TITLE
robotgo.TypeString() do not support utf-8

### ISSUE THREAD

**Issue by 2654709623** [go-vgo/robotgo#63]
package main

import (
	"github.com/go-vgo/robotgo"
	"time"
)

func main() {
	time.Sleep(3*time.Second)
	robotgo.TypeString("测试")
}
以上代码显示为空

**Comment by vCaesar** [comment]
Please see [issues/50](https://github.com/go-vgo/robotgo/issues/50), I will add it in future.

**Comment by vCaesar** [comment]
Closed because of duplication and non-standard.
