### ISSUE TITLE
"RobotGo: DragSmooth Operation Not Triggering hook.MouseDrag Event on macOS Sonoma"

### ISSUE THREAD

**Issue by wangxiaore888** [go-vgo/robotgo#637]
Subject: Issue with DragSmooth Not Triggering hook.MouseDrag Event on macOS Sonoma

Robotgo version: v0.110.0
Gohook version: v0.41.0
Go version: 1.21.5
Operating system and bit: macOS Sonoma 14.2.1 (23C71)
Resolution: N/A

Provide example code:

```
package main

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-vgo/robotgo"
	hook "github.com/robotn/gohook"
)

func main() {
	go func() {
		time.Sleep(3 * time.Second)
		robotgo.Move(480, 250)
		robotgo.Sleep(3)
		robotgo.Click("left", true)
		robotgo.Sleep(3)
		robotgo.DragSmooth(505, 447)
		robotgo.Sleep(10)
		hook.End()
	}()

	hook.Register(hook.MouseDrag, []string{}, func(e hook.Event) {
		jsonByte, _ := json.Marshal(e)
		fmt.Printf("MouseDown :%v \n", string(jsonByte))
	})
	s := hook.Start()
	<-hook.Process(s)
}
```

Description
I'm encountering an issue with RobotGo where using DragSmooth to perform a drag operation does not trigger the hook.MouseDrag event. However, when I perform the drag operation manually with a real mouse, the event is triggered as expected. This behavior occurs on macOS Sonoma. Could you please help me understand why DragSmooth is not triggering the hook.MouseDrag event and how I might resolve this issue? Any insights or suggestions would be greatly appreciated.

**Comment by a13x212** [comment]
@wangxiaore888 i'm having a similar issue. Did you find a solution?
