### ISSUE TITLE
When I build my goscript to exe, the function of robotgo dosen't take effect. how to resolve?

### ISSUE THREAD

**Issue by designplusplus** [go-vgo/robotgo#64]
1. Please speak English, this is the language everybody of us can speak and write.
2. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-vgo/robotgo
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Robotgo version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code: 
    ```Go

    ```
- Log gist:

## Description

...

**Comment by vCaesar** [comment]
I tested on the Windows 7 + go1.8.3, there is no problem. If you are convinced there is a robotgo problem, please tell us precisely how we can reproduce the problem ourselves.
