### ISSUE TITLE
Not run code by packages `robotgo` and `gcv`

### ISSUE THREAD

**Issue by Almazatun** [go-vgo/robotgo#657]
- Robotgo version (or commit ref): v1.0.0-beta5.3
- Go version: v1.22.0
- Gcc version: 15.0.0 (clang-1500.3.9.4)
- Operating system and bit: macOS Sonoma v14.5
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
	"github.com/vcaesar/gcv"
)

func main() {
	targetImage := "../assets/image.png"

	img, _, err := robotgo.DecodeImg(targetImage)

	if err != nil {
		panic(err)
	}

	screen := robotgo.CaptureImg()

	x, y := gcv.FindX(screen, img)
	fmt.Println(x, y)
}
```
- Log gist:

## Description
```
I just tried to get `x, y` coordination by image on the captured screen, but faced issues below when running code.
```
...
![image](https://github.com/go-vgo/robotgo/assets/50825098/c7705ab2-5032-4ac5-ba0c-536285004b19)

**Comment by a13x212** [comment]
Try using the latest version. [v0.110.1](https://github.com/go-vgo/robotgo/releases/tag/v0.110.1)

**Comment by Almazatun** [comment]
> Try using the latest version. [v0.110.1](https://github.com/go-vgo/robotgo/releases/tag/v0.110.1)

Thanks, I just ran `go get -u github.com/go-vgo/robotgo`. This is updated version of `robotgo` in `go.mod`.
