### ISSUE TITLE
fatal error: X11/Xlib.h: No such file or directory

### ISSUE THREAD

**Issue by kxjhlele** [go-vgo/robotgo#66]
Windows 10
golang 1.8.3
msys2

go get github.com/go-vgo/robotgo
# github.com/go-vgo/robotgo
In file included from ./screen/goScreen.h:12:0,
                 from D:\Home\go\src\github.com\go-vgo\robotgo\robotgo.go:36:
./screen/screengrab_c.h:11:23: fatal error: X11/Xlib.h: No such file or directory
  #include <X11/Xlib.h>
                       ^
compilation terminated.

**Comment by vCaesar** [comment]
Please read README.md and install dependencies.

**Comment by dlintw** [comment]
got the same issue
Windows 7
golang 1.12.5
msys2

In msys2, there is no libx11 package.
