### ISSUE TITLE
GOARCH=arm64 GOOS=linux go build main.go

### ISSUE THREAD

**Issue by zouchengli** [go-vgo/robotgo#670]
GOARCH=arm64 GOOS=linux go build main.go

# github.com/go-vgo/robotgo
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/img.go:92:40: undefined: Bitmap
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/img.go:107:38: undefined: Bitmap
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/img.go:137:20: undefined: Bitmap
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/screen.go:26:28: undefined: Rect
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/robotgo_fn_v1.go:9:2: undefined: Move
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/robotgo_fn_v1.go:17:2: undefined: Toggle
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/robotgo_fn_v1.go:18:2: undefined: MilliSleep
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/robotgo_fn_v1.go:20:2: undefined: MoveSmooth
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/robotgo_fn_v1.go:21:2: undefined: Toggle
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/robotgo_fn_v1.go:29:9: undefined: MoveSmooth
../../go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/robotgo_fn_v1.go:29:9: too many errors

**Comment by zouchengli** [comment]
PS Z:\GolandProjects\go-vgo\robotgo> go run .\examples\screen\main.go
go: downloading github.com/tailscale/win v0.0.0-20240403170916-6580b55d49ca
go: downloading github.com/vcaesar/gops v0.40.0
go: downloading golang.org/x/sys v0.20.0
go: downloading github.com/shirou/gopsutil/v4 v4.24.5
go: downloading github.com/dblohm7/wingoes v0.0.0-20231019175336-f6e33aa7cc34
go: downloading github.com/yusufpapurcu/wmi v1.2.4
# github.com/go-vgo/robotgo
.\img.go:92:40: undefined: Bitmap
.\img.go:107:38: undefined: Bitmap
.\img.go:137:20: undefined: Bitmap
.\screen.go:26:28: undefined: Rect
.\robotgo_fn_v1.go:9:2: undefined: Move
.\robotgo_fn_v1.go:17:2: undefined: Toggle
.\robotgo_fn_v1.go:18:2: undefined: MilliSleep
.\robotgo_fn_v1.go:20:2: undefined: MoveSmooth
.\robotgo_fn_v1.go:21:2: undefined: Toggle
.\robotgo_fn_v1.go:29:9: undefined: MoveSmooth
.\robotgo_fn_v1.go:29:9: too many errors

**Comment by DehaiWang** [comment]
i  build for windows  in Ubuntu ,  
```
sudo apt-get install mingw-w64

GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -o main.exe
```
