### ISSUE TITLE
`Move()` not work correctly

### ISSUE THREAD

**Issue by aohanhongzhi** [go-vgo/robotgo#688]
https://github.com/user-attachments/assets/e416946f-526c-483d-a075-8bb14491abe8

1. Please **speak English (English only)**, this is the language everybody of us can speak and write.
2. Please take a moment to **search** that an issue **doesn't already exist**.
3. Please make sure `Golang, GCC` is installed correctly before installing RobotGo.

5. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Robotgo version (or commit ref):v0.110.1
- Go version: 1.23.0
- Gcc version:  tdm64-1 10.3.0 
- Operating system and bit: windows11
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [X] Not relevant
- Provide example code:

```Go

func TestMoveClick1(t *testing.T) {
    robotgo.MoveSmooth(164, 38, 1.0, 10.0)
    time.Sleep(1 * time.Second)
    x, y := robotgo.Location()
    fmt.Println("pos: ", x, y)
}

```
- Log gist:

## Description

...

**Comment by xuehaonan27** [comment]
You MUST delete the content above including this line before posting, otherwise your issue will be invalid.
