### ISSUE TITLE
There is way to listener all keyboard input event?

### ISSUE THREAD

**Issue by gouez** [go-vgo/robotgo#69]
- Robotgo version (or commit ref): last

**Comment by vCaesar** [comment]
Please see [issues/21](https://github.com/go-vgo/robotgo/issues/21) and [issues/61](https://github.com/go-vgo/robotgo/issues/61), I will think about it or add it in future.

**Comment by vcaesar** [comment]
@iann0036 Thanks for support, which will be implemented in v.0.47.0 or v0.48.0

**Comment by vcaesar** [comment]
Have not found a good program, I think again.

**Comment by senro** [comment]
a node module named "iohook" can do the same thing, may be it can provide some idea!
