### ISSUE TITLE
cannot type C.int as type robotgo.C.int in argument to robotgo.MoveMouse

### ISSUE THREAD

**Issue by Vashnak** [go-vgo/robotgo#7]
Hi

I'm trying to use your lib but i'm getting this error.
cannot use C.int(x) (type C.int) as type robotgo.C.int in argument to robotgo.MoveMouse
What I am doing wrong ? 

Thx you :)

**Comment by vCaesar** [comment]
What is your system?32 or 64?I update test,it is no problem

**Comment by Vashnak** [comment]
I'm using ubuntu 16.04 64 bits.

I would like to get the position from robotogo.GetMousePos(). Stock it and reuse it later with robotgoGo.MoveMouse().

So i tried to convert it into C.int, but it doesn't seem to work

**Comment by vCaesar** [comment]
ok,I see,i will fix it

**Comment by vCaesar** [comment]
I fix it now

**Comment by vCaesar** [comment]
If it is ok,I will close this.

**Comment by Vashnak** [comment]
yeah that seems to be okay, thank you :)
