### ISSUE TITLE
Feature Request: MoveMouseRelative

### ISSUE THREAD

**Issue by elonzh** [go-vgo/robotgo#71]
References:

- [Relative mouse movement and CoreWindow](https://docs.microsoft.com/en-us/windows/uwp/gaming/relative-mouse-movement)
- [AutoHotKey-MouseMove](https://autohotkey.com/docs/commands/MouseMove.htm)

**Comment by vcaesar** [comment]
Ok, Thank you for your suggestion, I will think about it or add it in future.

**Comment by vcaesar** [comment]
Closing is due to code updated.
