### ISSUE TITLE
Installation requirements (GCC, zlib and libpng) only for development?

### ISSUE THREAD

**Issue by nkev** [go-vgo/robotgo#72]
- Robotgo version (or commit ref): irrelevant
- Go version: 1.8
- Gcc version: ?
- Operating system and bit: Mac, Windows 64, Linux
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [X] Not relevant

## Description
Are the installation requirements (GCC, zlib and libpng) only for development or are they required to be  pre-installed by end user? In other words, once I build a Go executable for (Windows, Linux and Mac) , is that all the user needs or do they need to pre-install the dependencies? It might be worthwhile to update the home page documentation for newbies, to avoid misunderstandings.

**Comment by vcaesar** [comment]
Thank you for your suggestion, I will think about it or add it in future.

**Comment by nkev** [comment]
What about my question though? Are the installation requirements (GCC, zlib and libpng) only for development or are they required to be pre-installed by end user?

**Comment by vcaesar** [comment]
Because it is dynamic link, the need for users to install in advance, perhaps remove it will be better or improved. If you do not need bitmap, you can switch to the robot branch

**Comment by vcaesar** [comment]
But in Windows is statically linked, you do not need pre-installed. Just on the mac, you need it.

**Comment by nkev** [comment]
Thanks. If it's dynamically linked on Mac, is it possible to include the libraries in the executable path for mac without installation? I am trying to make it easy to install for the user (simple installation).

**Comment by vcaesar** [comment]
The loading path is  "/usr/local/opt/libpng/lib/...", let me think how to make it better. Now, I want to fix findbitmap, maybe in the near future will change it.
