### ISSUE TITLE
Feature Request: SetActiveByName/ByPid

### ISSUE THREAD

**Issue by mailoman** [go-vgo/robotgo#73]
Is there any way to make Window active by process name found? or/and by pid?
I've just tried  
`
	pids, _ := robotgo.FindIds("gogland")
`
`	if err == nil && len(pids)>0 {
`
`		robotgo.ActivePID(pids[0])
` 
`    }
`
without any success.
Where I'm wrong?

- Go version: 1.8.1
- OS: Mac OS X 10.12.6

**Comment by vcaesar** [comment]
I will test it.

**Comment by seongmin-kim** [comment]
Testing some APIs, I stucked at 'ActivatePID', as well.
This problem, also, exists on [this repo](https://github.com/Robot/robot/blob/master/Source/Window.cc#L1795).

\# __file__ /window/window.h __line__ 565
```
if (AXUIElementPerformAction (win.AxID,
				  kAXRaiseAction) == kAXErrorSuccess)
	{
```

Obviously, the `AUUIElementPerformAction` method is used to perform action.
`then-phrase` works as error handler.
Therefore, this condition must be modified to '!=' operator.
```
if (AXUIElementPerformAction (win.AxID,
				  kAXRaiseAction) != kAXErrorSuccess)
	{
```
I hope you to understand my bad English.

**Comment by vcaesar** [comment]
Thanks for your advice, I will read the code and update it.

**Comment by lukeRGG** [comment]
Hi there,

any news on this issue? I'm experiencing the same problem: function called and executed correctly but without the desired effect, which is activating a window starting from pid.

**Comment by vcaesar** [comment]
Effective on the mac, no desired effect on the windows system.
