### ISSUE TITLE
GetTitle in window/window.h may return address of local variable

### ISSUE THREAD

**Issue by rakete** [go-vgo/robotgo#76]
- 6f13aded25f66137f426358815127fc0787a6688:
- go1.8.1 windows/amd64:
- 6.3.0:
- Windows 10:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [x] Not relevant

I just installed robotgo on windows and received the following warning:

    C:\Users\Rakete
    λ go get github.com/go-vgo/robotgo
    # github.com/go-vgo/robotgo
    Desktop\go\src\github.com\go-vgo\robotgo/window/window.h: In function 'GetTitle.part.16':
    cc1.exe: warning: function may return address of local variable [-Wreturn-local-addr]
    In file included from Desktop\go\src\github.com\go-vgo\robotgo/window/goWindow.h:12:0,
                     from Desktop\go\src\github.com\go-vgo\robotgo\robotgo.go:41:
    Desktop\go\src\github.com\go-vgo\robotgo/window/window.h:860:8: note: declared here
      TCHAR name[512];
            ^~~~

And looking at the relevant lines in window/window.h:

    TCHAR name[512];                                
    return GetWindowText                            
        (mData.HWnd, name, 512) > 0 ? name : "null";

It does indeed seem like returning the local TCHAR *name pointer when the result of GetWindowText(...) > 0 is an issue there.

**Comment by vcaesar** [comment]
I will test it, should be and in my computer no problem.

**Comment by rakete** [comment]
I've looked at the GetTitle() function a little closer and I believe there are multiple problems with it. On Mac OS you call calloc and then return the allocated pointer, but you never call C.free in the wrapper function defined in robotgo.go:908, which means there is a memory leak.

The X11 version of the GetTitle() function does call XFree on the allocated memory, but without making a proper copy first. So you are just making a copy of the pointer, then free'ing the memory and returning the copy of the pointer to the now free'd memory.

And what is a caller supposed to do with the returned pointer? Normally you would assume that GetTitle() allocates memory and the caller would be responsible for calling free on that memory. But depending on the operating system you are on this would be (sometimes) OK on Mac OS, cause a double free on Linux and a segmentation fault on Windows.

Additionally you return string literals, and calling free on them would also be a segmentation fault.

I've been thinking about rewriting the whole function and sending you a pull request. It will take me a week or so because I need to find the time though. Would you be interested in that?

**Comment by vcaesar** [comment]
Yeap, everyone's time is limited, thanks for your advice and work.

**Comment by DeeCen** [comment]
go1.9 windows/386
Windows 7
MinGW 32

I got the same message "go-vgo\robotgo/window/window.h: In function 'GetTitle.part.21"
the file github.com\go-vgo\robotgo/window/window.h  LINE 823  the code "return s"  change to "return *s" will be DONE

**Comment by vcaesar** [comment]
This problem only appears in the higher gcc version.
