### ISSUE TITLE
combination keys `ctrl+s` does not work

### ISSUE THREAD

**Issue by weaming** [go-vgo/robotgo#77]
I installed all requirements, my environment is osx.

But the key combination `ctrl+s` does not work, while other normal keytap work normally
My code:
https://gist.github.com/weaming/da4cf0cf78f4c58b13de05b3e489d38f

**Comment by vcaesar** [comment]
ctrl+s or robotgo.KeyTap("s", "command") ?

**Comment by weaming** [comment]
`robotgo.KeyTap("s", "command")` works on Windows but failed on OSX

**Comment by vcaesar** [comment]
This is the system shortcut key.
