### ISSUE TITLE
Bitmap related

### ISSUE THREAD

**Issue by iMaxopoly** [go-vgo/robotgo#79]
Hi,

Thank you for the great library, this was much needed.

I have a request if we can get a bitmap version of GetColor, where we can pass golang's bitmap struct. It becomes tedious or impossible to pass the result bitmap image from BCaptureScreen from one function to another. If you have any alternative solutions, kindly help.

Thanks again.

**Comment by vcaesar** [comment]
Let me think about it.

**Comment by vcaesar** [comment]
Closed because of the new API before several versions, you can convert go bitmap struct to c bitmap. You can use robotgo.ToCbitmap().
