### ISSUE TITLE
菜鸟求教软件运行问题

### ISSUE THREAD

**Issue by geekjunyi** [go-vgo/robotgo#9]
`package main

import (
	. "fmt"

	"github.com/go-vgo/robotgo"
)

func main() {
	robotgo.MoveMouse(800, 0)

	for i := 0; i < 1080; i += 1000 {
		Println(i)
		robotgo.MoveMouse(800, i)
	}
}
`
提示错误`.\main.go:14: cannot use i (type int) as type robotgo._Ctype_size_t in argument to robotgo.MoveMouse`
请问.MoveMouse(x, y)的参数为什么不设为int类型？
在循环里面没有办法直接使用int变量给方法传参数？

**Comment by vCaesar** [comment]
I see,I will make all c.type to go.type

**Comment by vCaesar** [comment]
I fix it,if ok i will close this.

**Comment by geekjunyi** [comment]
问题已经解决！谢谢！
