### ISSUE TITLE
I want to move the mouse smooth and quickly.

### ISSUE THREAD

**Issue by wilon** [go-vgo/robotgo#96]
```go
l, h := 5.0, 500.0
MoveSmooth(800, 500, l, h)
```
I change the params `l h` in many times, but it still slow. 
Such as `0, 0` move to `800, 500`, almost `> 2s`.

I want to move the mouse smooth and quickly. Such as `0, 0` move to `1200, 800` in `< 1s`. How?

**Comment by vcaesar** [comment]
I will test it or update it.

**Comment by vcaesar** [comment]
`robotgo.MoveSmooth(800, 500, 0.5, 1.0, 0)`.
