### ISSUE TITLE
How to add multiple keypress event listener ?

### ISSUE THREAD

**Issue by wilon** [go-vgo/robotgo#98]
I want `press k` do something, and `press s` do something.

I try it like this, but failed.
```go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {

	kCh := make(chan int)
	go func() {
		for {
			fmt.Println("...event k")
			kCh <- robotgo.AddEvent("k")
		}
	}()

	sCh := make(chan int)
	go func() {
		for {
			fmt.Println("...event s")
			sCh <- robotgo.AddEvent("s")
		}
	}()

	for {
		switch {
		case <-kCh == 0:
			fmt.Println("you press...", "k")
		case <-sCh == 0:
			fmt.Println("you press...", "s")
		}
		fmt.Println("for switch")
	}
}

```

**Comment by vcaesar** [comment]
I will test it and think about how to do it, and I'll fix it if there is a problem.

**Comment by Mebus** [comment]
I want something similar, but with left and right mouse button.

**Comment by bonly** [comment]
yes, me too, it is ahk style use

**Comment by vcaesar** [comment]
I will update it or give me a PR.

**Comment by wilon** [comment]
I'm sorry, I'm incapable for write `C`.

The func `robotgo.AddEvent("v")` is lock the system key listen. 
https://github.com/go-vgo/robotgo/blob/master/event/goEvent.h#L69

https://github.com/go-vgo/robotgo/blob/master/event/goEvent.h#L152
I suggest to add func ——

    string key_listener() {}        // C: goEvent.h, return the keypress string
    func keyListener() string {}    // Go: robotgo.go

Then I can use it like this:
```golang
for {
	switch robotgo.keyListener() {
	case "k":
		fmt.Println("--- You press v---", "v")
	case "v":
		fmt.Println("--- You press k---", "k")
	}
}
```

I hope it will help you.

**Comment by afdalwahyu** [comment]
hi @wilon i have the same problem too,
to the one still having same problem maybe [this package](https://github.com/go-xkg/xkg) could help

**Comment by JuicyASen** [comment]
same issue here, and it will be very nice to have a keyDown/Up listener.

**Comment by wbzqe** [comment]
same issue here..  like  'ctrl+a'

**Comment by vcaesar** [comment]
The code will be tested further and will be submitted within a week.

**Comment by vcaesar** [comment]
```Go
fmt.Println("--- Please press ctrl + shift + q ---")
ok := robotgo.AddEvents("q", "ctrl", "shift")
if ok {
	fmt.Println("add events...")
}
```
