### ISSUE TITLE
一开始就报错了，不知道怎么办

### ISSUE THREAD

**Issue by zhangwei0530** [go-vgo/robotgo#99]
func main() {
	robotgo.TypeString("Hello World")
	robotgo.KeyTap("enter")
	robotgo.TypeString("en")
	robotgo.KeyTap("i", "alt", "command")
	arr := []string{"alt", "command"}
	robotgo.KeyTap("i", arr)
	robotgo.WriteAll("测试")
	text, err := robotgo.ReadAll()
	if err == nil {
		fmt.Println(text)
	}
}

//控制台打印

# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2:0,
                 from ./bitmap/goBitmap.h:27,
                 from ..\github.com\go-vgo\robotgo\robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
compilation terminated.

**Comment by vcaesar** [comment]
What is your system version and bit? And please use English, thx.

**Comment by zhangwei0530** [comment]
I used the window7 professional version of the 64 - bit operating system, installed the GCC and successfully run the golang code。

**Comment by vcaesar** [comment]
The GCC compiler's file may be the problem, please use `mingw`.

**Comment by vcaesar** [comment]
Please see #100, if the same problem occurs, please tell me how to reproduce it.
